// Future Map — all survey content lives here so it is easy to edit.

// The 10 topics. Every question answer and every job is tagged with these.
const TOPICS = {
  sci: { name: "Science & Discovery",   icon: "🔬" },
  tec: { name: "Technology & Computers", icon: "💻" },
  bld: { name: "Building & Fixing",      icon: "🔧" },
  art: { name: "Art & Design",           icon: "🎨" },
  prf: { name: "Performing & Media",     icon: "🎭" },
  hlp: { name: "Helping & Health",       icon: "🩺" },
  nat: { name: "Nature & Animals",       icon: "🌿" },
  spo: { name: "Sports & Action",        icon: "⚽" },
  biz: { name: "Business & Money",       icon: "💰" },
  wrd: { name: "Words & Teaching",       icon: "📚" },
};

// Things to try now, by age group: little (5–8), middle (9–12), teen (13–18).
const TIPS = {
  sci: ["Do kitchen experiments like baking soda volcanoes and ask 'why?' a lot.",
        "Join a science club or enter a science fair.",
        "Take biology, chemistry, physics and math. Look for summer science camps."],
  tec: ["Play simple coding games like ScratchJr or code.org puzzles.",
        "Learn Scratch, then try making a small game or website.",
        "Take computer science, learn Python or JavaScript, and build a real project."],
  bld: ["Build with blocks, LEGO and cardboard boxes.",
        "Take apart old gadgets with an adult and try a robotics kit.",
        "Take shop, design or engineering classes, or look at apprenticeships."],
  art: ["Draw, paint and make crafts every week.",
        "Keep a sketchbook and try digital drawing apps.",
        "Take art and design classes and start a portfolio of your best work."],
  prf: ["Put on shows for your family and sing or dance for fun.",
        "Join the school play, choir, band, or make short videos.",
        "Take drama, music or media classes and perform whenever you can."],
  hlp: ["Help at home and be a kind friend at school.",
        "Learn basic first aid and volunteer with your family.",
        "Take biology and health classes, and volunteer at a hospital or care home."],
  nat: ["Plant seeds, visit parks, and learn animal facts.",
        "Look after a pet or garden and join nature clubs.",
        "Take biology and environmental science, and volunteer at a shelter or park."],
  spo: ["Run, jump, swim and try lots of different sports.",
        "Join a team and practise the sport you like most.",
        "Train seriously, take PE and health classes, and try coaching younger kids."],
  biz: ["Play store and count coins. Try saving up for something.",
        "Run a lemonade or craft stand and track what you earn.",
        "Take economics or business classes, and try a part-time job or small business."],
  wrd: ["Read every day and make up your own stories.",
        "Write a diary, join a book club, and help younger kids read.",
        "Take English and a new language. Join debate or the school newspaper."],
};

// 20 questions. Each answer adds 1 point to one topic (each topic can score 0–8).
const QUESTIONS = [
  { q: "It's a free Saturday. What do you want to do?", a: [
    ["🏰", "Build a fort or take apart an old toy", "bld"],
    ["🏀", "Play a sport outside", "spo"],
    ["🖍️", "Draw, paint or make crafts", "art"],
    ["📖", "Read a book or write a story", "wrd"] ] },
  { q: "Pick a school trip.", a: [
    ["🧪", "A science museum", "sci"],
    ["🐧", "A zoo or aquarium", "nat"],
    ["🎭", "A theater show", "prf"],
    ["🏪", "A market to see how buying and selling works", "biz"] ] },
  { q: "Which superpower would you choose?", a: [
    ["🩹", "Heal anyone who is hurt", "hlp"],
    ["🦊", "Talk to animals", "nat"],
    ["🤖", "Control computers with your mind", "tec"],
    ["⚡", "Super speed", "spo"] ] },
  { q: "Which school subject do you like best?", a: [
    ["➗", "Math", "sci"],
    ["🎨", "Art", "art"],
    ["🔤", "Reading and languages", "wrd"],
    ["🖥️", "Computers and coding", "tec"] ] },
  { q: "Your friend is sad. What do you do?", a: [
    ["🤗", "Listen and help them feel better", "hlp"],
    ["🤡", "Put on a funny show to make them laugh", "prf"],
    ["💌", "Write them a nice card", "wrd"],
    ["⚽", "Take them outside to play a game", "spo"] ] },
  { q: "What would you most like to make?", a: [
    ["🤖", "A robot", "tec"],
    ["🌳", "A treehouse", "bld"],
    ["💥", "A comic book", "art"],
    ["🍋", "A lemonade stand that earns money", "biz"] ] },
  { q: "Which question do you most want answered?", a: [
    ["🌈", "Why is the sky blue?", "sci"],
    ["🐝", "How do bees make honey?", "nat"],
    ["💵", "How do businesses make money?", "biz"],
    ["🎮", "How do you make a video game?", "tec"] ] },
  { q: "At a party, you are the one who…", a: [
    ["🎤", "Sings or dances for everyone", "prf"],
    ["📋", "Plans the party and runs the snack table", "biz"],
    ["🫶", "Makes sure nobody is left out", "hlp"],
    ["🔌", "Fixes the speaker when it breaks", "bld"] ] },
  { q: "Where would you like to spend your day?", a: [
    ["🏥", "A hospital", "hlp"],
    ["🚜", "A forest or a farm", "nat"],
    ["🎬", "A stage or film studio", "prf"],
    ["🧰", "A workshop full of tools", "bld"] ] },
  { q: "Pick a video to watch.", a: [
    ["🧫", "Amazing science experiments", "sci"],
    ["🏆", "Sports highlights", "spo"],
    ["✏️", "How to draw cool characters", "art"],
    ["🐉", "Someone telling a great story", "wrd"] ] },
  { q: "Which present would you like best?", a: [
    ["🧱", "Building blocks or LEGO", "bld"],
    ["🧪", "A chemistry or slime kit", "sci"],
    ["🎲", "A board game about money, like Monopoly", "biz"],
    ["📱", "A tablet with coding games", "tec"] ] },
  { q: "In a group project, you'd rather…", a: [
    ["🗣️", "Present it to the class", "prf"],
    ["📝", "Write the report", "wrd"],
    ["🖼️", "Make the poster look great", "art"],
    ["🤝", "Help teammates who are stuck", "hlp"] ] },
  { q: "What would you most like to take care of?", a: [
    ["🌻", "A garden full of plants", "nat"],
    ["👧", "A younger kid learning to read", "wrd"],
    ["🤒", "A friend who feels sick", "hlp"],
    ["🥅", "A sports team", "spo"] ] },
  { q: "Which sounds the most fun?", a: [
    ["🔬", "Looking through a microscope", "sci"],
    ["🧗", "Climbing a mountain", "spo"],
    ["🌟", "Starring in a movie", "prf"],
    ["👗", "Designing your own clothes", "art"] ] },
  { q: "Someone gives you $100. What do you do?", a: [
    ["🐷", "Save it and try to make it grow", "biz"],
    ["🎨", "Buy art supplies", "art"],
    ["🐶", "Give it to an animal shelter", "nat"],
    ["🔋", "Buy parts to build a gadget", "tec"] ] },
  { q: "What would you like to be famous for?", a: [
    ["💡", "Discovering something new", "sci"],
    ["💖", "Being really kind and helpful", "hlp"],
    ["🥇", "Being a great athlete", "spo"],
    ["🧑‍🏫", "Explaining things so everyone understands", "wrd"] ] },
  { q: "Which problem would you fix first?", a: [
    ["🌊", "Dirty oceans", "nat"],
    ["🌉", "Old, broken bridges and buildings", "bld"],
    ["👩‍⚕️", "People who can't see a doctor", "hlp"],
    ["🛡️", "Hackers stealing information", "tec"] ] },
  { q: "In your free time, you like to…", a: [
    ["🎸", "Sing, play music or act", "prf"],
    ["🪛", "Tinker and invent gadgets", "bld"],
    ["🔄", "Sell or trade things", "biz"],
    ["📓", "Write in a diary or make up poems", "wrd"] ] },
  { q: "Pick a uniform you'd like to wear.", a: [
    ["🥼", "A lab coat", "sci"],
    ["⛑️", "A hard hat and tool belt", "bld"],
    ["🎽", "A sports jersey", "spo"],
    ["🎪", "A costume on stage", "prf"] ] },
  { q: "Last one! Your dream day at work is…", a: [
    ["✨", "Designing something beautiful", "art"],
    ["🐾", "Helping animals and nature", "nat"],
    ["🏢", "Running your own company", "biz"],
    ["👾", "Building an app or a game", "tec"] ] },
];

// Every job: [name, what they do, topics with importance, years of training after 18, outlook]
// Topic importance: 3 = comes first, 2 = important, 1 = helps too.
// Outlook: g = growing, s = steady, c = changing (robots/AI will change it), f = future job.
const JOBS = [
  // Science & Discovery
  ["Astronaut", "Travels to space to run experiments and fix spacecraft", "sci3 tec2 spo1", 8, "g"],
  ["Chemist", "Mixes substances to invent new materials and medicines", "sci3 tec1 hlp1", 4, "s"],
  ["Physicist", "Studies how energy, light and motion work", "sci3 tec2 wrd1", 8, "s"],
  ["Astronomer", "Studies stars, planets and galaxies with telescopes", "sci3 tec2 nat1", 9, "s"],
  ["Biologist", "Studies living things, from tiny cells to whole animals", "sci3 nat2 wrd1", 4, "s"],
  ["Marine Biologist", "Studies ocean animals and plants", "nat3 sci3 spo1", 4, "s"],
  ["Geologist", "Studies rocks, volcanoes and earthquakes", "sci3 nat2 bld1", 4, "s"],
  ["Meteorologist", "Predicts the weather and studies storms", "sci3 nat2 prf1", 4, "s"],
  ["Lab Technician", "Runs tests on samples in a science lab", "sci3 tec1 hlp1", 2, "c"],
  ["Archaeologist", "Digs up clues about how people lived long ago", "sci3 wrd2 nat1", 6, "s"],
  ["Paleontologist", "Finds and studies dinosaur fossils", "sci3 nat2 wrd1", 8, "s"],
  ["Forensic Scientist", "Uses science to solve crimes", "sci3 hlp2 tec1", 4, "s"],
  ["Pharmacist", "Prepares medicines and explains how to take them", "sci3 hlp2 biz1", 6, "s"],
  ["Research Scientist", "Runs experiments to discover new things", "sci3 wrd2 tec1", 9, "g"],
  ["Climate Scientist", "Studies how Earth's climate is changing", "sci3 nat2 tec1", 6, "g"],
  ["Mathematician", "Solves hard number puzzles that help science and tech", "sci3 tec2 wrd1", 6, "g"],
  ["Statistician", "Finds patterns in numbers and data", "sci3 tec2 biz1", 4, "g"],
  ["Botanist", "Studies plants and how they grow", "sci3 nat3", 4, "s"],
  ["Oceanographer", "Explores the ocean, its currents and its floor", "sci3 nat2 tec1", 6, "s"],
  ["Food Scientist", "Makes food safer, tastier and healthier", "sci3 hlp1 art1", 4, "s"],
  ["Inventor", "Dreams up new gadgets and figures out how to make them", "bld3 sci2 biz1", 0, "g"],

  // Technology & Computers
  ["Software Developer", "Writes the code that runs apps and websites", "tec3 sci1 bld1", 4, "g"],
  ["Video Game Developer", "Creates video games people love to play", "tec3 art2 prf1", 4, "g"],
  ["UX / App Designer", "Designs apps so they are easy and fun to use", "art3 tec2 hlp1", 4, "g"],
  ["Data Scientist", "Uses computers to find answers hidden in huge amounts of data", "tec3 sci2 biz1", 4, "g"],
  ["AI Engineer", "Builds smart computer programs that can learn", "tec3 sci2 bld1", 6, "g"],
  ["Cybersecurity Expert", "Protects computers and people from hackers", "tec3 hlp1 sci1", 4, "g"],
  ["Robotics Engineer", "Designs and builds robots", "bld3 tec3 sci1", 4, "g"],
  ["Web Designer", "Designs and builds websites", "tec3 art2 biz1", 2, "c"],
  ["IT Support Technician", "Fixes computers and helps people with tech problems", "tec3 hlp2 bld1", 2, "s"],
  ["Network Engineer", "Keeps the internet and computer networks running", "tec3 bld1 sci1", 4, "s"],
  ["Drone Pilot", "Flies drones to film, map and deliver things", "tec3 spo1 nat1", 1, "g"],
  ["Computer Hardware Engineer", "Designs computer chips and devices", "tec3 bld2 sci1", 4, "s"],
  ["Game Tester", "Plays games early to find bugs", "tec3 prf1 wrd1", 0, "c"],
  ["Social Media Manager", "Runs social media accounts for companies", "wrd3 tec2 biz1", 4, "g"],
  ["Cloud Engineer", "Runs the giant computers that store everyone's apps and photos", "tec3 bld1 biz1", 4, "g"],

  // Building & Fixing
  ["Architect", "Designs houses, schools and skyscrapers", "bld3 art2 sci1", 6, "s"],
  ["Civil Engineer", "Plans bridges, roads and tunnels", "bld3 sci2 nat1", 4, "s"],
  ["Mechanical Engineer", "Designs machines, engines and gadgets", "bld3 sci2 tec1", 4, "s"],
  ["Aerospace Engineer", "Designs airplanes and rockets", "bld3 sci2 tec2", 4, "g"],
  ["Electrical Engineer", "Designs circuits and power systems", "bld3 tec2 sci1", 4, "g"],
  ["Carpenter", "Builds things out of wood, from shelves to houses", "bld3 art1 spo1", 3, "s"],
  ["Electrician", "Installs and fixes wiring and lights", "bld3 tec1 hlp1", 4, "g"],
  ["Plumber", "Fixes pipes, sinks and water heaters", "bld3 hlp2", 4, "s"],
  ["Car Mechanic", "Fixes cars and keeps them running safely", "bld3 tec2", 2, "c"],
  ["Electric Vehicle Technician", "Repairs electric cars and charging stations", "bld3 tec2 nat1", 2, "g"],
  ["Welder", "Joins metal together with super-hot flames", "bld3 art1", 2, "s"],
  ["Construction Worker", "Builds houses, roads and buildings", "bld3 spo2", 0, "s"],
  ["Construction Manager", "Leads the team building a big project", "bld3 biz2 wrd1", 4, "g"],
  ["Bricklayer / Stonemason", "Builds walls and buildings from brick and stone", "bld3 art1 spo1", 2, "s"],
  ["Solar Panel Installer", "Puts solar panels on roofs to make clean energy", "bld3 nat2 tec1", 1, "g"],
  ["Wind Turbine Technician", "Climbs and repairs giant wind turbines", "bld3 nat2 spo1", 2, "g"],
  ["Aircraft Mechanic", "Inspects and repairs airplanes", "bld3 tec2 sci1", 2, "s"],
  ["Interior Designer", "Makes rooms look great and work well", "art3 bld2 biz1", 4, "s"],
  ["Landscape Architect", "Designs parks, gardens and playgrounds", "nat3 art2 bld2", 4, "s"],
  ["Locksmith", "Opens, fixes and installs locks", "bld3 hlp1", 1, "s"],
  ["Shipbuilder", "Builds and repairs boats and ships", "bld3 spo1 nat1", 3, "s"],
  ["Train Driver", "Drives trains safely on time", "tec2 bld2 hlp1", 1, "c"],
  ["Truck Driver", "Drives trucks to deliver goods across the country", "bld2 spo1 biz1", 0, "c"],

  // Art & Design
  ["Artist / Painter", "Creates paintings and artwork", "art3 biz1", 0, "s"],
  ["Illustrator", "Draws pictures for books, games and ads", "art3 wrd1 tec1", 4, "c"],
  ["Graphic Designer", "Designs logos, posters and packages", "art3 tec2 biz1", 4, "c"],
  ["Animator", "Brings cartoons and movie characters to life", "art3 tec2 prf1", 4, "g"],
  ["Fashion Designer", "Designs clothes, shoes and accessories", "art3 biz2 bld1", 4, "s"],
  ["Photographer", "Takes photos for magazines, weddings and events", "art3 tec1 nat1", 2, "s"],
  ["Sculptor", "Makes art from clay, stone and metal", "art3 bld2", 0, "s"],
  ["Tattoo Artist", "Draws permanent art on skin", "art3 biz2", 1, "s"],
  ["Jewelry Maker", "Designs and makes rings, necklaces and bracelets", "art3 bld2 biz1", 1, "s"],
  ["Cartoonist / Comic Artist", "Draws comics and funny cartoons", "art3 wrd2 prf1", 0, "s"],
  ["Florist", "Arranges flowers into beautiful bouquets", "art3 nat2 biz1", 0, "s"],
  ["Hairstylist", "Cuts, colors and styles hair", "art3 hlp2 biz1", 1, "s"],
  ["Makeup Artist", "Does makeup for movies, shows and events", "art3 prf2 hlp1", 1, "s"],
  ["Chef", "Cooks delicious meals in a restaurant kitchen", "art3 biz1 spo1", 2, "s"],
  ["Baker / Pastry Chef", "Bakes bread, cakes and desserts", "art3 bld1 biz1", 2, "s"],
  ["Toy Designer", "Invents and designs new toys", "art3 bld2 biz1", 4, "s"],
  ["Car Designer", "Designs how new cars look", "art3 bld2 tec1", 4, "s"],
  ["Museum Curator", "Chooses and cares for museum collections", "art3 wrd2 sci1", 6, "s"],
  ["Video Editor", "Cuts and puts together videos and movies", "art3 tec2 prf1", 2, "g"],
  ["Theater Set Designer", "Builds the scenery for plays and shows", "art3 bld2 prf1", 4, "s"],
  ["Potter", "Shapes clay into bowls, mugs and vases", "art3 bld1 biz1", 0, "s"],

  // Performing & Media
  ["Actor", "Plays characters in movies, TV and theater", "prf3 wrd1 art1", 0, "s"],
  ["Singer", "Sings songs on stage and in recordings", "prf3 art1", 0, "s"],
  ["Musician", "Plays instruments in bands and orchestras", "prf3 art2", 0, "s"],
  ["Dancer", "Performs dances on stage and in videos", "prf3 spo2 art1", 0, "s"],
  ["Film Director", "Leads the team that makes a movie", "prf3 art2 wrd1", 4, "s"],
  ["Content Creator / YouTuber", "Makes videos and posts for people online", "prf3 tec2 biz1", 0, "g"],
  ["TV Presenter / News Anchor", "Hosts shows and reads the news on TV", "prf3 wrd2", 4, "s"],
  ["Podcaster / Radio Host", "Talks, interviews people and plays music for listeners", "prf3 wrd2 tec1", 0, "g"],
  ["Comedian", "Makes people laugh with jokes and stories", "prf3 wrd2", 0, "s"],
  ["Magician", "Amazes audiences with magic tricks", "prf3 art1 biz1", 0, "s"],
  ["Circus Performer", "Does acrobatics, juggling and tricks", "prf3 spo2", 0, "s"],
  ["Music Producer", "Records and mixes songs in a studio", "prf3 tec2 art1", 2, "g"],
  ["Sound Engineer", "Controls the sound at concerts and in studios", "tec3 prf2", 2, "s"],
  ["Composer", "Writes music for movies, games and orchestras", "art2 prf3 tec1", 4, "s"],
  ["DJ", "Mixes music for parties and radio", "prf3 tec1 biz1", 0, "s"],
  ["Voice Actor", "Gives voices to cartoon and game characters", "prf3 wrd2", 0, "c"],
  ["Esports Player", "Plays video games in tournaments", "tec3 prf2 spo1", 0, "g"],
  ["Stunt Performer", "Does dangerous action scenes in movies", "spo3 prf2", 0, "s"],
  ["Camera Operator", "Films movies, TV shows and sports", "prf3 tec2 art1", 2, "s"],
  ["Journalist", "Finds out what is happening and reports the news", "wrd3 prf1 hlp1", 4, "c"],

  // Helping & Health
  ["Doctor", "Finds out why people are sick and helps them get better", "hlp3 sci2 wrd1", 8, "g"],
  ["Children's Doctor (Pediatrician)", "Takes care of babies and kids", "hlp3 sci2 wrd1", 11, "g"],
  ["Surgeon", "Does operations to fix people's bodies", "hlp3 sci2 bld1", 11, "g"],
  ["Nurse", "Cares for patients in hospitals and clinics", "hlp3 sci2 spo1", 4, "g"],
  ["Dentist", "Keeps teeth healthy and fixes cavities", "hlp3 sci2 bld1", 8, "s"],
  ["Paramedic", "Rushes to emergencies in an ambulance", "hlp3 spo2 sci1", 2, "g"],
  ["Firefighter", "Puts out fires and rescues people", "hlp3 spo2 bld1", 1, "s"],
  ["Police Officer", "Keeps communities safe and helps people in trouble", "hlp3 spo2 wrd1", 1, "s"],
  ["Psychologist", "Helps people understand their thoughts and feelings", "hlp3 wrd2 sci1", 8, "g"],
  ["School Counselor", "Helps students with problems and plans for the future", "hlp3 wrd2", 6, "g"],
  ["Social Worker", "Helps families get what they need to be safe and healthy", "hlp3 wrd2", 4, "g"],
  ["Physical Therapist", "Helps people move again after injuries", "hlp3 spo2 sci1", 7, "g"],
  ["Speech Therapist", "Helps people learn to talk and communicate", "hlp3 wrd2 sci1", 6, "g"],
  ["Optometrist", "Checks eyes and gives people glasses", "hlp3 sci2 tec1", 8, "s"],
  ["Midwife", "Helps mothers when babies are born", "hlp3 sci1", 4, "s"],
  ["Caregiver", "Looks after older people or people with disabilities", "hlp3", 0, "g"],
  ["Dietitian", "Helps people eat healthy food", "hlp3 sci2 spo1", 4, "g"],
  ["Lifeguard", "Watches swimmers and saves people in the water", "spo3 hlp2 nat1", 0, "s"],
  ["Soldier", "Protects the country and helps in disasters", "spo3 hlp2 tec1", 0, "s"],
  ["Emergency Dispatcher", "Answers emergency calls and sends help", "hlp3 tec1 wrd1", 0, "s"],
  ["Flight Attendant", "Keeps passengers safe and comfortable on planes", "hlp3 spo1 wrd1", 0, "s"],
  ["Sign Language Interpreter", "Translates between spoken and sign language", "wrd3 hlp2", 4, "s"],
  ["Lawyer", "Helps people understand the law and speaks for them in court", "wrd3 hlp2 biz1", 7, "c"],
  ["Judge", "Listens to both sides in court and makes fair decisions", "wrd3 hlp2", 10, "s"],
  ["Sports Medicine Doctor", "Treats athletes' injuries", "hlp3 spo2 sci1", 11, "g"],

  // Nature & Animals
  ["Veterinarian", "Takes care of sick and hurt animals", "nat3 hlp2 sci2", 8, "g"],
  ["Vet Nurse", "Helps the vet care for animals", "nat3 hlp2 sci1", 2, "g"],
  ["Zookeeper", "Feeds and cares for zoo animals", "nat3 hlp1 spo1", 2, "s"],
  ["Farmer", "Grows food and raises animals", "nat3 bld1 biz1", 0, "c"],
  ["Park Ranger", "Protects national parks and teaches visitors", "nat3 spo2 hlp1", 4, "s"],
  ["Wildlife Photographer", "Photographs wild animals in nature", "nat3 art2 spo1", 0, "s"],
  ["Gardener / Landscaper", "Plants and cares for gardens and lawns", "nat3 bld1 art1", 0, "s"],
  ["Environmental Scientist", "Finds ways to protect air, water and land", "nat3 sci2 wrd1", 4, "g"],
  ["Dog Trainer", "Teaches dogs to behave and do tricks", "nat3 hlp1 biz1", 0, "s"],
  ["Animal Rescuer", "Saves and rehomes animals in trouble", "nat3 hlp2", 0, "s"],
  ["Horse Riding Instructor", "Teaches people to ride and care for horses", "nat3 spo2 wrd1", 1, "s"],
  ["Fisher", "Catches fish to sell for food", "nat3 spo1 biz1", 0, "c"],
  ["Beekeeper", "Takes care of bees and collects honey", "nat3 biz1 sci1", 0, "s"],
  ["Forester", "Looks after forests and plants new trees", "nat3 spo1 sci1", 4, "s"],
  ["Pet Groomer", "Washes, brushes and trims pets", "nat3 art1 hlp1", 1, "s"],
  ["Storm Chaser", "Follows tornadoes and big storms to study them", "nat3 sci2 spo2", 4, "s"],
  ["Wildlife Biologist", "Tracks and protects wild animals", "nat3 sci2 spo1", 6, "g"],

  // Sports & Action
  ["Professional Athlete", "Plays a sport as a job and competes to win", "spo3 prf1", 0, "s"],
  ["Coach", "Trains a team and helps players improve", "spo3 wrd2 hlp1", 2, "s"],
  ["Personal Trainer", "Helps people get fit and strong", "spo3 hlp2 biz1", 1, "g"],
  ["Sports Referee", "Makes sure games are played fairly", "spo3 wrd1", 1, "s"],
  ["PE Teacher", "Teaches kids sports and fitness at school", "spo3 wrd2 hlp1", 4, "s"],
  ["Mountain Guide", "Leads climbers and hikers safely up mountains", "spo3 nat2 hlp1", 2, "s"],
  ["Scuba Diving Instructor", "Teaches people to dive underwater", "spo3 nat2 wrd1", 1, "s"],
  ["Ski Instructor", "Teaches people to ski and snowboard", "spo3 wrd1 nat1", 1, "s"],
  ["Sports Commentator", "Describes the action during games on TV and radio", "spo3 prf2 wrd1", 2, "s"],
  ["Race Car Driver", "Drives super-fast cars in races", "spo3 tec1 bld1", 0, "s"],
  ["Martial Arts Instructor", "Teaches karate, judo or taekwondo", "spo3 wrd1 hlp1", 1, "s"],
  ["Yoga Instructor", "Teaches yoga to help people relax and stay healthy", "spo3 hlp2", 1, "g"],
  ["Sports Scientist", "Uses science to help athletes perform better", "spo3 sci2 hlp1", 4, "g"],
  ["Pilot", "Flies airplanes full of passengers or cargo", "tec3 spo2 sci1", 3, "s"],
  ["Tour Guide", "Shows visitors around cities and places", "wrd3 prf2 spo1", 0, "s"],

  // Business & Money
  ["Entrepreneur", "Starts and runs a new business", "biz3 wrd1 tec1", 0, "g"],
  ["Accountant", "Keeps track of money for people and companies", "biz3 sci1 tec1", 4, "c"],
  ["Banker", "Helps people save, borrow and look after money", "biz3 wrd1", 4, "c"],
  ["Financial Advisor", "Helps families plan how to use their money", "biz3 hlp2 wrd1", 4, "s"],
  ["Marketing Manager", "Gets people excited about new products", "biz3 wrd2 art1", 4, "s"],
  ["Salesperson", "Helps customers find and buy what they need", "biz3 wrd2 prf1", 0, "c"],
  ["Real Estate Agent", "Helps people buy and sell houses", "biz3 wrd1 bld1", 1, "s"],
  ["Store Manager", "Runs a shop and leads the team", "biz3 hlp1 wrd1", 0, "s"],
  ["Economist", "Studies how money moves around the world", "biz3 sci2 wrd1", 6, "s"],
  ["Stock Trader", "Buys and sells shares of companies", "biz3 tec2 sci1", 4, "c"],
  ["Event Planner", "Plans weddings, parties and festivals", "biz3 art2 prf1", 2, "s"],
  ["Hotel Manager", "Runs a hotel and makes guests happy", "biz3 hlp2 wrd1", 4, "s"],
  ["Restaurant Owner", "Runs a restaurant, from menu to money", "biz3 art1 hlp1", 0, "s"],
  ["Human Resources Manager", "Hires people and helps workers be happy", "biz3 hlp2 wrd1", 4, "s"],
  ["Product Manager", "Decides what a new app or product should do", "biz3 tec2 wrd1", 4, "g"],
  ["Project Manager", "Keeps big projects on track and on time", "biz3 wrd1 bld1", 4, "g"],
  ["Company CEO", "Leads a whole company and makes the big decisions", "biz3 wrd2 tec1", 10, "s"],
  ["Logistics Manager", "Figures out how to get things shipped around the world", "biz3 tec1 bld1", 4, "g"],
  ["Politician / Mayor", "Leads a town or country and makes laws", "wrd3 hlp2 biz1", 4, "s"],

  // Words & Teaching
  ["Teacher", "Helps kids learn new things every day", "wrd3 hlp2", 4, "s"],
  ["Kindergarten Teacher", "Teaches young kids to read, count and play together", "wrd3 hlp2 art1", 4, "s"],
  ["Professor", "Teaches at a university and does research", "wrd3 sci2", 9, "s"],
  ["Author", "Writes books and stories", "wrd3 art2", 0, "c"],
  ["Children's Book Author", "Writes and sometimes draws books for kids", "wrd3 art2 hlp1", 0, "s"],
  ["Librarian", "Helps people find books and information", "wrd3 hlp1 tec1", 6, "c"],
  ["Translator", "Changes words from one language to another", "wrd3 biz1", 4, "c"],
  ["Editor", "Checks and improves writing before it is published", "wrd3 biz1 art1", 4, "c"],
  ["Screenwriter", "Writes the scripts for movies and TV shows", "wrd3 prf2 art1", 0, "s"],
  ["Poet / Songwriter", "Writes poems and song lyrics", "wrd3 art2 prf1", 0, "s"],
  ["Historian", "Studies and writes about the past", "wrd3 sci1", 8, "s"],
  ["Diplomat", "Represents their country and helps nations get along", "wrd3 hlp1 biz1", 6, "s"],
  ["School Principal", "Leads a whole school", "wrd3 hlp2 biz1", 8, "s"],
  ["Tutor", "Helps students one-on-one with schoolwork", "wrd3 hlp1", 0, "g"],
  ["Copywriter", "Writes the words for ads and websites", "wrd3 biz2", 4, "c"],
  ["Language Teacher", "Teaches people to speak new languages", "wrd3 hlp1", 4, "s"],

  // Future jobs (may be much bigger by the time you grow up)
  ["AI Trainer", "Teaches AI systems to be helpful, safe and correct", "tec3 wrd2 sci1", 2, "f"],
  ["Space Tourism Guide", "Takes travelers on trips to space", "spo3 prf2 sci1", 4, "f"],
  ["Climate Engineer", "Builds machines that clean the air and cool the planet", "bld3 nat2 sci2", 4, "f"],
  ["Drone Traffic Controller", "Keeps thousands of delivery drones from crashing", "tec3 hlp1", 2, "f"],
  ["Virtual World Designer", "Designs 3D worlds people explore in VR", "art3 tec2 prf1", 4, "f"],
  ["Robot Repair Technician", "Fixes robots in homes, farms and factories", "bld3 tec2", 2, "f"],
  ["Mars Habitat Builder", "Builds homes for people living on Mars", "bld3 sci2 spo1", 6, "f"],
  ["Gene Therapist", "Fixes diseases by repairing DNA", "sci3 hlp2 tec1", 9, "f"],
  ["Ocean Cleanup Specialist", "Runs machines that pull plastic out of the ocean", "nat3 bld1 hlp1", 2, "f"],
  ["Digital Privacy Advisor", "Helps people keep their data safe online", "tec3 wrd2 hlp1", 4, "f"],
  ["Virtual Event Host", "Runs concerts and events inside virtual worlds", "prf3 tec2 biz1", 0, "f"],
  ["Health Data Coach", "Uses smartwatch data to help people stay healthy", "hlp3 tec2 spo1", 4, "f"],
  ["Smart City Planner", "Designs cities with self-driving cars and clean energy", "bld3 tec2 hlp1", 6, "f"],
  ["Space Farmer", "Grows food on space stations and other planets", "nat3 sci2 tec1", 4, "f"],
  ["Human-Robot Team Manager", "Leads teams where people and robots work together", "biz3 tec2 hlp1", 4, "f"],
  ["3D Food Printing Chef", "Designs meals made with food printers", "art3 tec2 sci1", 2, "f"],
];
