// Future Map — every job the game can guess.
// Every job: [name, what they do, topics with importance, years of training after 18, outlook]
// Topic importance: 3 = comes first, 2 = important, 1 = helps too.
// Outlook: g = growing, s = steady, c = changing (robots/AI will change it), f = future job.
const JOBS = [
  // Science
  ["Astronaut", "Travels to space to run experiments and fix spacecraft", "spc3 sci2 spo1", 8, "g"],
  ["Chemist", "Mixes substances to invent new materials and medicines", "sci3 hlp1", 4, "s"],
  ["Physicist", "Studies how energy, light and motion work", "sci3 tec1 spc1", 8, "s"],
  ["Astronomer", "Studies stars, planets and galaxies with telescopes", "spc3 sci3 tec1", 9, "s"],
  ["Biologist", "Studies living things, from tiny cells to whole animals", "sci3 ani2 nat1", 4, "s"],
  ["Marine Biologist", "Studies ocean animals and plants", "ani3 sci2 adv1", 4, "s"],
  ["Geologist", "Studies rocks, volcanoes and earthquakes", "sci3 nat2 adv1", 4, "s"],
  ["Meteorologist", "Predicts the weather and studies storms", "sci3 nat2 mda1", 4, "s"],
  ["Lab Technician", "Runs tests on samples in a science lab", "sci3 hlp1", 2, "c"],
  ["Archaeologist", "Digs up clues about how people lived long ago", "sci3 adv2 wrd1", 6, "s"],
  ["Paleontologist", "Finds and studies dinosaur fossils", "sci3 adv2 ani1", 8, "s"],
  ["Forensic Scientist", "Uses science to solve crimes", "sci3 saf2 lea1", 4, "s"],
  ["Pharmacist", "Prepares medicines and explains how to take them", "hlp3 sci2 biz1", 6, "s"],
  ["Research Scientist", "Runs experiments to discover new things", "sci3 wrd1 tec1", 9, "g"],
  ["Climate Scientist", "Studies how Earth's climate is changing", "nat3 sci3 tec1", 6, "g"],
  ["Mathematician", "Solves hard number puzzles that help science and tech", "sci3 tec2 tea1", 6, "g"],
  ["Statistician", "Finds patterns in numbers and data", "sci3 tec2 biz1", 4, "g"],
  ["Botanist", "Studies plants and how they grow", "nat3 sci3", 4, "s"],
  ["Oceanographer", "Explores the ocean, its currents and its floor", "sci3 adv2 nat2", 6, "s"],
  ["Food Scientist", "Makes food safer, tastier and healthier", "fod3 sci3 hlp1", 4, "s"],
  ["Inventor", "Dreams up new gadgets and figures out how to make them", "bld3 sci2 biz1", 0, "g"],

  // Technology
  ["Software Developer", "Writes the code that runs apps and websites", "tec3 sci1 bld1", 4, "g"],
  ["Video Game Developer", "Creates video games people love to play", "tec3 mda3 art1", 4, "g"],
  ["UX / App Designer", "Designs apps so they are easy and fun to use", "art3 tec2 car1", 4, "g"],
  ["Data Scientist", "Uses computers to find answers hidden in huge amounts of data", "tec3 sci2 biz1", 4, "g"],
  ["AI Engineer", "Builds smart computer programs that can learn", "tec3 sci2 bld1", 6, "g"],
  ["Cybersecurity Expert", "Protects computers and people from hackers", "tec3 saf2 sci1", 4, "g"],
  ["Robotics Engineer", "Designs and builds robots", "bld3 tec3 mec2", 4, "g"],
  ["Web Designer", "Designs and builds websites", "tec3 art2 biz1", 2, "c"],
  ["IT Support Technician", "Fixes computers and helps people with tech problems", "tec3 car1 mec1", 2, "s"],
  ["Network Engineer", "Keeps the internet and computer networks running", "tec3 bld1", 4, "s"],
  ["Drone Pilot", "Flies drones to film, map and deliver things", "mec3 tec2 mda1", 1, "g"],
  ["Computer Hardware Engineer", "Designs computer chips and devices", "tec3 bld2 sci1", 4, "s"],
  ["Game Tester", "Plays games early to find bugs", "mda3 tec2", 0, "c"],
  ["Social Media Manager", "Runs social media accounts for companies", "mda3 biz2 wrd1", 4, "g"],
  ["Cloud Engineer", "Runs the giant computers that store everyone's apps and photos", "tec3 bld1 biz1", 4, "g"],

  // Building & machines
  ["Architect", "Designs houses, schools and skyscrapers", "bld3 art2 sci1", 6, "s"],
  ["Civil Engineer", "Plans bridges, roads and tunnels", "bld3 sci2 saf1", 4, "s"],
  ["Mechanical Engineer", "Designs machines, engines and gadgets", "mec3 bld3 sci1", 4, "s"],
  ["Aerospace Engineer", "Designs airplanes and rockets", "spc3 bld3 sci2", 4, "g"],
  ["Electrical Engineer", "Designs circuits and power systems", "bld3 tec2 sci1", 4, "g"],
  ["Carpenter", "Builds things out of wood, from shelves to houses", "bld3 art1", 3, "s"],
  ["Electrician", "Installs and fixes wiring and lights", "bld3 mec2 saf1", 4, "g"],
  ["Plumber", "Fixes pipes, sinks and water heaters", "bld3 mec2 car1", 4, "s"],
  ["Car Mechanic", "Fixes cars and keeps them running safely", "mec3 bld1", 2, "c"],
  ["Electric Vehicle Technician", "Repairs electric cars and charging stations", "mec3 tec2 nat1", 2, "g"],
  ["Welder", "Joins metal together with super-hot flames", "bld3 mec2", 2, "s"],
  ["Construction Worker", "Builds houses, roads and buildings", "bld3 mec2 spo1", 0, "s"],
  ["Construction Manager", "Leads the team building a big project", "bld3 lea2 biz1", 4, "g"],
  ["Crane Operator", "Lifts huge loads high above building sites", "mec3 bld2 saf1", 1, "s"],
  ["Bricklayer / Stonemason", "Builds walls and buildings from brick and stone", "bld3 art1", 2, "s"],
  ["Solar Panel Installer", "Puts solar panels on roofs to make clean energy", "bld3 nat2", 1, "g"],
  ["Wind Turbine Technician", "Climbs and repairs giant wind turbines", "mec3 nat2 adv1", 2, "g"],
  ["Aircraft Mechanic", "Inspects and repairs airplanes", "mec3 spc2", 2, "s"],
  ["Interior Designer", "Makes rooms look great and work well", "art3 bld2 biz1", 4, "s"],
  ["Landscape Architect", "Designs parks, gardens and playgrounds", "nat3 art2 bld2", 4, "s"],
  ["Locksmith", "Opens, fixes and installs locks", "mec3 saf1", 1, "s"],
  ["Shipbuilder", "Builds and repairs boats and ships", "bld3 mec2 adv1", 3, "s"],
  ["Ship Captain", "Steers big ships across the oceans", "mec3 adv3 lea2", 4, "s"],
  ["Train Driver", "Drives trains safely on time", "mec3 saf1", 1, "c"],
  ["Truck Driver", "Drives trucks to deliver goods across the country", "mec3 adv1", 0, "c"],
  ["Pilot", "Flies airplanes full of passengers or cargo", "spc3 mec3 adv1", 3, "s"],
  ["Air Traffic Controller", "Guides planes safely in the sky and on the runway", "spc3 saf2 tec1", 3, "s"],

  // Art & design
  ["Artist / Painter", "Creates paintings and artwork", "art3 biz1", 0, "s"],
  ["Illustrator", "Draws pictures for books, games and ads", "art3 wrd1", 4, "c"],
  ["Graphic Designer", "Designs logos, posters and packages", "art3 tec1 biz1", 4, "c"],
  ["Animator", "Brings cartoons and movie characters to life", "art3 mda3 tec1", 4, "g"],
  ["Fashion Designer", "Designs clothes, shoes and accessories", "art3 biz2", 4, "s"],
  ["Photographer", "Takes photos for magazines, weddings and events", "art3 mda2", 2, "s"],
  ["Sculptor", "Makes art from clay, stone and metal", "art3 bld2", 0, "s"],
  ["Tattoo Artist", "Draws permanent art on skin", "art3 biz1", 1, "s"],
  ["Jewelry Maker", "Designs and makes rings, necklaces and bracelets", "art3 bld1 biz1", 1, "s"],
  ["Cartoonist / Comic Artist", "Draws comics and funny cartoons", "art3 wrd2 mda1", 0, "s"],
  ["Florist", "Arranges flowers into beautiful bouquets", "art3 nat2 biz1", 0, "s"],
  ["Hairstylist", "Cuts, colors and styles hair", "art3 car1 biz1", 1, "s"],
  ["Makeup Artist", "Does makeup for movies, shows and events", "art3 mda2", 1, "s"],
  ["Toy Designer", "Invents and designs new toys", "art3 bld2 biz1", 4, "s"],
  ["Car Designer", "Designs how new cars look", "art3 mec2 bld1", 4, "s"],
  ["Museum Curator", "Chooses and cares for museum collections", "art3 wrd2 tea1", 6, "s"],
  ["Video Editor", "Cuts and puts together videos and movies", "mda3 tec2 art1", 2, "g"],
  ["Theater Set Designer", "Builds the scenery for plays and shows", "art3 bld2 prf1", 4, "s"],
  ["Potter", "Shapes clay into bowls, mugs and vases", "art3 biz1", 0, "s"],

  // Food
  ["Chef", "Cooks delicious meals in a restaurant kitchen", "fod3 art1 lea1", 2, "s"],
  ["Baker / Pastry Chef", "Bakes bread, cakes and desserts", "fod3 art2", 2, "s"],
  ["Restaurant Owner", "Runs a restaurant, from menu to money", "fod3 biz3 lea1", 0, "s"],
  ["Food Truck Owner", "Cooks and sells food from a truck", "fod3 biz2 adv1", 0, "g"],
  ["Food Critic", "Tries restaurants and writes reviews", "fod3 wrd2 mda1", 0, "s"],
  ["Cooking Show Host", "Cooks on TV or online and teaches recipes", "fod3 mda2 prf1", 0, "s"],
  ["Chocolatier", "Makes fancy chocolates and sweets", "fod3 art2 biz1", 1, "s"],

  // Performing & media
  ["Actor", "Plays characters in movies, TV and theater", "prf3 mda2", 0, "s"],
  ["Singer", "Sings songs on stage and in recordings", "prf3", 0, "s"],
  ["Musician", "Plays instruments in bands and orchestras", "prf3 art1", 0, "s"],
  ["Music Teacher", "Teaches kids to sing and play instruments", "prf3 tea3", 4, "s"],
  ["Dancer", "Performs dances on stage and in videos", "prf3 spo2", 0, "s"],
  ["Film Director", "Leads the team that makes a movie", "mda3 lea2 prf1", 4, "s"],
  ["Content Creator / YouTuber", "Makes videos and posts for people online", "mda3 prf2 biz1", 0, "g"],
  ["TV Presenter / News Anchor", "Hosts shows and reads the news on TV", "mda3 prf2 wrd1", 4, "s"],
  ["Podcaster / Radio Host", "Talks, interviews people and plays music for listeners", "mda3 wrd2", 0, "g"],
  ["Comedian", "Makes people laugh with jokes and stories", "prf3 wrd2", 0, "s"],
  ["Magician", "Amazes audiences with magic tricks", "prf3 art1", 0, "s"],
  ["Circus Performer", "Does acrobatics, juggling and tricks", "prf3 spo2 adv1", 0, "s"],
  ["Music Producer", "Records and mixes songs in a studio", "prf3 tec2 mda1", 2, "g"],
  ["Sound Engineer", "Controls the sound at concerts and in studios", "tec3 prf2 mda1", 2, "s"],
  ["Composer", "Writes music for movies, games and orchestras", "prf3 art2 mda1", 4, "s"],
  ["DJ", "Mixes music for parties and radio", "prf3 tec1 mda1", 0, "s"],
  ["Voice Actor", "Gives voices to cartoon and game characters", "prf3 mda2", 0, "c"],
  ["Esports Player", "Plays video games in tournaments", "mda3 spo2 tec1", 0, "g"],
  ["Stunt Performer", "Does dangerous action scenes in movies", "spo3 mda2 adv1", 0, "s"],
  ["Camera Operator", "Films movies, TV shows and sports", "mda3 tec1 art1", 2, "s"],
  ["Journalist", "Finds out what is happening and reports the news", "wrd3 mda2 lea1", 4, "c"],
  ["Documentary Filmmaker", "Makes true-story films about the real world", "mda3 adv2 wrd1", 2, "s"],

  // Health
  ["Doctor", "Finds out why people are sick and helps them get better", "hlp3 sci2 car1", 8, "g"],
  ["Children's Doctor (Pediatrician)", "Takes care of babies and kids", "hlp3 car2 sci1", 11, "g"],
  ["Surgeon", "Does operations to fix people's bodies", "hlp3 sci2", 11, "g"],
  ["Nurse", "Cares for patients in hospitals and clinics", "hlp3 car2 sci1", 4, "g"],
  ["Dentist", "Keeps teeth healthy and fixes cavities", "hlp3 sci1", 8, "s"],
  ["Paramedic", "Rushes to emergencies in an ambulance", "saf3 hlp3", 2, "g"],
  ["Psychologist", "Helps people understand their thoughts and feelings", "car3 hlp2 sci1", 8, "g"],
  ["Physical Therapist", "Helps people move again after injuries", "hlp3 spo2", 7, "g"],
  ["Speech Therapist", "Helps people learn to talk and communicate", "hlp3 tea2 wrd1", 6, "g"],
  ["Optometrist", "Checks eyes and gives people glasses", "hlp3 sci2", 8, "s"],
  ["Midwife", "Helps mothers when babies are born", "hlp3 car2", 4, "s"],
  ["Dietitian", "Helps people eat healthy food", "hlp3 fod2 sci1", 4, "g"],
  ["Sports Medicine Doctor", "Treats athletes' injuries", "hlp3 spo2 sci1", 11, "g"],

  // Caring & community
  ["Caregiver", "Looks after older people or people with disabilities", "car3 hlp1", 0, "g"],
  ["Social Worker", "Helps families get what they need to be safe and healthy", "car3 lea1", 4, "g"],
  ["School Counselor", "Helps students with problems and plans for the future", "car3 tea2", 6, "g"],
  ["Youth Worker", "Runs clubs and activities for kids and teens", "car3 tea2 spo1", 2, "s"],
  ["Charity Organizer", "Raises money and runs projects to help people", "car3 biz2 lea1", 4, "s"],
  ["Sign Language Interpreter", "Translates between spoken and sign language", "wrd3 car2", 4, "s"],
  ["Flight Attendant", "Keeps passengers safe and comfortable on planes", "adv3 car2 saf1", 0, "s"],
  ["Hotel Manager", "Runs a hotel and makes guests happy", "biz3 car2 adv1", 4, "s"],

  // Safety & rescue
  ["Firefighter", "Puts out fires and rescues people", "saf3 spo2", 1, "s"],
  ["Police Officer", "Keeps communities safe and helps people in trouble", "saf3 lea2 car1", 1, "s"],
  ["Detective", "Solves mysteries and crimes", "saf3 sci1 lea1", 3, "s"],
  ["Lifeguard", "Watches swimmers and saves people in the water", "saf3 spo2", 0, "s"],
  ["Soldier", "Protects the country and helps in disasters", "saf3 spo2 adv1", 0, "s"],
  ["Coast Guard Rescuer", "Saves people at sea from boats and helicopters", "saf3 adv2 mec1", 1, "s"],
  ["Search and Rescue Pilot", "Flies helicopters to find lost and hurt people", "saf3 mec2 spc1", 3, "s"],
  ["Emergency Dispatcher", "Answers emergency calls and sends help", "saf3 car2", 0, "s"],
  ["Safety Inspector", "Checks buildings and factories to keep people safe", "saf3 bld2", 4, "s"],

  // Leading & law
  ["Lawyer", "Helps people understand the law and speaks for them in court", "lea3 wrd2", 7, "c"],
  ["Judge", "Listens to both sides in court and makes fair decisions", "lea3 wrd1", 10, "s"],
  ["Politician / Mayor", "Leads a town or country and makes laws", "lea3 car2 prf1", 4, "s"],
  ["Diplomat", "Represents their country and helps nations get along", "lea3 adv2 wrd1", 6, "s"],
  ["Company CEO", "Leads a whole company and makes the big decisions", "lea3 biz3", 10, "s"],
  ["School Principal", "Leads a whole school", "lea3 tea2 car1", 8, "s"],
  ["Human Resources Manager", "Hires people and helps workers be happy", "lea3 car2 biz1", 4, "s"],
  ["Project Manager", "Keeps big projects on track and on time", "lea3 biz2", 4, "g"],

  // Business & money
  ["Entrepreneur", "Starts and runs a new business", "biz3 lea2 tec1", 0, "g"],
  ["Accountant", "Keeps track of money for people and companies", "biz3 sci1", 4, "c"],
  ["Banker", "Helps people save, borrow and look after money", "biz3", 4, "c"],
  ["Financial Advisor", "Helps families plan how to use their money", "biz3 car2", 4, "s"],
  ["Marketing Manager", "Gets people excited about new products", "biz3 mda2 art1", 4, "s"],
  ["Salesperson", "Helps customers find and buy what they need", "biz3 car1", 0, "c"],
  ["Real Estate Agent", "Helps people buy and sell houses", "biz3 bld1", 1, "s"],
  ["Store Manager", "Runs a shop and leads the team", "biz3 lea2", 0, "s"],
  ["Economist", "Studies how money moves around the world", "biz3 sci2", 6, "s"],
  ["Stock Trader", "Buys and sells shares of companies", "biz3 tec1 sci1", 4, "c"],
  ["Event Planner", "Plans weddings, parties and festivals", "biz3 art1 lea1", 2, "s"],
  ["Product Manager", "Decides what a new app or product should do", "biz3 tec2 lea1", 4, "g"],
  ["Logistics Manager", "Figures out how to get things shipped around the world", "biz3 adv1 mec1", 4, "g"],

  // Words & teaching
  ["Teacher", "Helps kids learn new things every day", "tea3 car2", 4, "s"],
  ["Kindergarten Teacher", "Teaches young kids to read, count and play together", "tea3 car2 art1", 4, "s"],
  ["Science Teacher", "Teaches experiments and how the world works", "tea3 sci2", 4, "s"],
  ["Professor", "Teaches at a university and does research", "tea3 sci2 wrd1", 9, "s"],
  ["Tutor", "Helps students one-on-one with schoolwork", "tea3 car1", 0, "g"],
  ["Language Teacher", "Teaches people to speak new languages", "tea3 wrd2 adv1", 4, "s"],
  ["Author", "Writes books and stories", "wrd3 art1", 0, "c"],
  ["Children's Book Author", "Writes and sometimes draws books for kids", "wrd3 art2", 0, "s"],
  ["Librarian", "Helps people find books and information", "wrd3 tea2", 6, "c"],
  ["Translator", "Changes words from one language to another", "wrd3 adv2", 4, "c"],
  ["Editor", "Checks and improves writing before it is published", "wrd3 mda1", 4, "c"],
  ["Screenwriter", "Writes the scripts for movies and TV shows", "wrd3 mda2 prf1", 0, "s"],
  ["Poet / Songwriter", "Writes poems and song lyrics", "wrd3 prf2", 0, "s"],
  ["Historian", "Studies and writes about the past", "wrd3 sci1 tea1", 8, "s"],
  ["Copywriter", "Writes the words for ads and websites", "wrd3 biz2", 4, "c"],

  // Nature & animals
  ["Veterinarian", "Takes care of sick and hurt animals", "ani3 hlp3 sci1", 8, "g"],
  ["Vet Nurse", "Helps the vet care for animals", "ani3 hlp2", 2, "g"],
  ["Zookeeper", "Feeds and cares for zoo animals", "ani3 car1", 2, "s"],
  ["Farmer", "Grows food and raises animals", "nat3 ani2 fod1", 0, "c"],
  ["Park Ranger", "Protects national parks and teaches visitors", "nat3 adv2 tea1", 4, "s"],
  ["Wildlife Photographer", "Photographs wild animals in nature", "ani3 mda2 adv2", 0, "s"],
  ["Gardener / Landscaper", "Plants and cares for gardens and lawns", "nat3 art1", 0, "s"],
  ["Environmental Scientist", "Finds ways to protect air, water and land", "nat3 sci2", 4, "g"],
  ["Dog Trainer", "Teaches dogs to behave and do tricks", "ani3 tea2", 0, "s"],
  ["Animal Rescuer", "Saves and rehomes animals in trouble", "ani3 car2 saf1", 0, "s"],
  ["Horse Riding Instructor", "Teaches people to ride and care for horses", "ani3 spo2 tea1", 1, "s"],
  ["Fisher", "Catches fish to sell for food", "nat3 adv1 fod1", 0, "c"],
  ["Beekeeper", "Takes care of bees and collects honey", "ani3 nat2 fod1", 0, "s"],
  ["Forester", "Looks after forests and plants new trees", "nat3 adv1", 4, "s"],
  ["Pet Groomer", "Washes, brushes and trims pets", "ani3 art1", 1, "s"],
  ["Storm Chaser", "Follows tornadoes and big storms to study them", "nat3 adv3 sci2", 4, "s"],
  ["Wildlife Biologist", "Tracks and protects wild animals", "ani3 sci2 nat2", 6, "g"],

  // Sports & adventure
  ["Professional Athlete", "Plays a sport as a job and competes to win", "spo3", 0, "s"],
  ["Coach", "Trains a team and helps players improve", "spo3 tea2 lea1", 2, "s"],
  ["Personal Trainer", "Helps people get fit and strong", "spo3 hlp2 biz1", 1, "g"],
  ["Sports Referee", "Makes sure games are played fairly", "spo3 lea2", 1, "s"],
  ["PE Teacher", "Teaches kids sports and fitness at school", "spo3 tea2", 4, "s"],
  ["Mountain Guide", "Leads climbers and hikers safely up mountains", "adv3 spo2 saf1", 2, "s"],
  ["Scuba Diving Instructor", "Teaches people to dive underwater", "adv3 spo2 ani1", 1, "s"],
  ["Ski Instructor", "Teaches people to ski and snowboard", "spo3 tea1 adv1", 1, "s"],
  ["Sports Commentator", "Describes the action during games on TV and radio", "spo3 mda2", 2, "s"],
  ["Race Car Driver", "Drives super-fast cars in races", "spo3 mec3", 0, "s"],
  ["Martial Arts Instructor", "Teaches karate, judo or taekwondo", "spo3 tea2", 1, "s"],
  ["Yoga Instructor", "Teaches yoga to help people relax and stay healthy", "spo3 hlp2", 1, "g"],
  ["Sports Scientist", "Uses science to help athletes perform better", "spo3 sci2 hlp1", 4, "g"],
  ["Tour Guide", "Shows visitors around cities and places", "adv3 tea1 wrd1", 0, "s"],
  ["Travel Writer", "Visits places around the world and writes about them", "adv3 wrd2 mda1", 0, "s"],
  ["Explorer / Expedition Leader", "Leads trips to wild, faraway places", "adv3 lea2 sci1", 2, "s"],

  // Future jobs (may be much bigger by the time you grow up)
  ["AI Trainer", "Teaches AI systems to be helpful, safe and correct", "tec3 wrd2 tea1", 2, "f"],
  ["Space Tourism Guide", "Takes travelers on trips to space", "spc3 adv3 car1", 4, "f"],
  ["Climate Engineer", "Builds machines that clean the air and cool the planet", "nat3 bld3 sci1", 4, "f"],
  ["Drone Traffic Controller", "Keeps thousands of delivery drones from crashing", "tec3 spc1 saf1", 2, "f"],
  ["Virtual World Designer", "Designs 3D worlds people explore in VR", "mda3 art2 tec2", 4, "f"],
  ["Robot Repair Technician", "Fixes robots in homes, farms and factories", "mec3 tec2", 2, "f"],
  ["Mars Habitat Builder", "Builds homes for people living on Mars", "spc3 bld3", 6, "f"],
  ["Gene Therapist", "Fixes diseases by repairing DNA", "hlp3 sci3", 9, "f"],
  ["Ocean Cleanup Specialist", "Runs machines that pull plastic out of the ocean", "nat3 mec1 adv1", 2, "f"],
  ["Digital Privacy Advisor", "Helps people keep their data safe online", "tec3 saf2 car1", 4, "f"],
  ["Virtual Event Host", "Runs concerts and events inside virtual worlds", "mda3 prf2 biz1", 0, "f"],
  ["Health Data Coach", "Uses smartwatch data to help people stay healthy", "hlp3 tec2 spo1", 4, "f"],
  ["Smart City Planner", "Designs cities with self-driving cars and clean energy", "bld3 tec2 lea1", 6, "f"],
  ["Space Farmer", "Grows food on space stations and other planets", "spc3 nat3 fod1", 4, "f"],
  ["Human-Robot Team Manager", "Leads teams where people and robots work together", "lea3 tec2", 4, "f"],
  ["3D Food Printing Chef", "Designs meals made with food printers", "fod3 tec2 art1", 2, "f"],
  ["Lab-Grown Meat Scientist", "Grows meat from cells so no animals are harmed", "fod3 sci3 ani1", 4, "f"],
  ["Self-Driving Car Engineer", "Teaches cars to drive themselves safely", "mec3 tec3 saf1", 4, "f"],

  // More science
  ["Microbiologist", "Studies tiny living things like bacteria", "sci3 hlp1", 4, "g"],
  ["Geneticist", "Studies genes and how traits pass from parents to kids", "sci3 hlp2", 8, "g"],
  ["Zoologist", "Studies how animals live and behave", "ani3 sci3", 4, "s"],
  ["Entomologist", "Studies insects and bugs", "ani3 sci2 nat1", 6, "s"],
  ["Volcanologist", "Studies volcanoes and eruptions", "sci3 nat2 adv2", 6, "s"],
  ["Seismologist", "Studies earthquakes", "sci3 nat2 saf1", 6, "s"],
  ["Hydrologist", "Studies rivers, lakes and water underground", "sci3 nat2", 4, "s"],
  ["Ecologist", "Studies how plants and animals live together", "nat3 sci2 ani1", 4, "g"],
  ["Materials Scientist", "Invents new stronger and lighter materials", "sci3 bld2", 6, "g"],
  ["Nanotechnologist", "Builds things too tiny to see", "sci3 tec2 bld1", 8, "f"],
  ["Neuroscientist", "Studies how the brain works", "sci3 hlp2", 9, "g"],
  ["Epidemiologist", "Tracks how diseases spread and how to stop them", "hlp3 sci3", 6, "g"],
  ["Biochemist", "Studies the chemistry inside living things", "sci3 hlp1", 6, "s"],
  ["Cartographer", "Makes maps of the world", "adv3 art2 tec1", 4, "c"],
  ["Surveyor", "Measures land before things are built", "bld3 adv1 tec1", 4, "s"],
  ["Toxicologist", "Finds out which substances are poisonous", "sci3 hlp2 saf1", 6, "s"],
  ["Science Journalist", "Writes news about new discoveries", "wrd3 sci2 mda1", 4, "s"],
  ["Chemical Engineer", "Designs factories that make chemicals and fuels", "sci3 bld2", 4, "s"],
  ["Nuclear Engineer", "Designs power plants that run on nuclear energy", "sci3 bld2 saf1", 6, "s"],
  ["Biomedical Engineer", "Designs machines that help doctors", "hlp3 bld2 sci2", 4, "g"],
  ["Quantum Computing Researcher", "Builds super-powerful new kinds of computers", "tec3 sci3", 9, "f"],
  ["Science Museum Explainer", "Shows visitors how science exhibits work", "sci3 tea2 prf1", 2, "s"],

  // More technology
  ["Mobile App Developer", "Builds apps for phones and tablets", "tec3 art1 biz1", 4, "g"],
  ["Front-End Developer", "Builds the parts of websites you see and click", "tec3 art2", 2, "g"],
  ["Back-End Developer", "Builds the hidden systems behind apps", "tec3 sci1", 4, "g"],
  ["Machine Learning Engineer", "Teaches computers to learn from examples", "tec3 sci2", 6, "g"],
  ["Database Administrator", "Keeps huge collections of data safe and organized", "tec3 biz1", 4, "s"],
  ["Systems Analyst", "Figures out how computers can help a company", "tec3 biz2", 4, "s"],
  ["Ethical Hacker", "Breaks into systems on purpose to find weak spots before criminals do", "tec3 saf2", 4, "g"],
  ["Computer Scientist", "Invents new ways for computers to solve problems", "tec3 sci3", 9, "g"],
  ["Game Designer", "Invents the rules, levels and story of a video game", "mda3 art2 tec1", 4, "g"],
  ["VR Developer", "Builds virtual reality worlds and experiences", "tec3 mda2 art1", 4, "g"],
  ["Blockchain Developer", "Builds secure digital money and records", "tec3 biz2", 4, "c"],
  ["Technical Writer", "Writes instructions that explain how technology works", "wrd3 tec2 tea1", 4, "c"],
  ["Help Desk Technician", "Answers calls and fixes tech problems for people", "tec3 car2", 1, "c"],
  ["Computer Repair Technician", "Fixes broken laptops, tablets and phones", "tec3 mec2", 1, "s"],
  ["Telecommunications Technician", "Installs phone and internet cables", "tec3 bld2 mec1", 2, "s"],
  ["Chip Designer", "Designs the tiny chips inside every gadget", "tec3 bld2 sci2", 6, "g"],
  ["Robotics Technician", "Builds and repairs robots in factories", "mec3 tec2", 2, "g"],
  ["Software Tester", "Tests apps to find bugs before people use them", "tec3 sci1", 2, "c"],

  // More building
  ["Structural Engineer", "Makes sure buildings and bridges won't fall down", "bld3 sci2 saf1", 4, "s"],
  ["Roofer", "Builds and repairs roofs", "bld3 adv1", 1, "s"],
  ["Painter and Decorator", "Paints houses and rooms", "bld3 art2", 1, "s"],
  ["Tiler", "Lays tiles on floors and walls", "bld3 art1", 2, "s"],
  ["Glazier", "Cuts and fits glass for windows", "bld3 art1", 2, "s"],
  ["Plasterer", "Smooths walls and ceilings", "bld3", 2, "s"],
  ["Heating and Cooling Technician", "Installs heaters and air conditioners", "bld3 mec2", 2, "g"],
  ["Heavy Equipment Operator", "Drives bulldozers, diggers and dump trucks", "mec3 bld2", 1, "s"],
  ["Urban Planner", "Plans how towns and cities grow", "bld3 lea2 nat1", 6, "s"],
  ["Drafter", "Draws detailed plans for buildings and machines", "bld3 art2 tec1", 2, "c"],
  ["Home Inspector", "Checks houses for problems before people buy them", "bld3 saf2", 2, "s"],
  ["Industrial Designer", "Designs everyday products like chairs and phones", "art3 bld3", 4, "s"],
  ["Environmental Engineer", "Designs ways to keep water and air clean", "bld3 nat3 sci1", 4, "g"],
  ["Mining Engineer", "Plans safe ways to dig minerals out of the ground", "bld3 sci1 saf1", 4, "s"],
  ["Geothermal Technician", "Uses heat from inside the Earth to make energy", "bld3 nat2 mec1", 2, "g"],
  ["Demolition Expert", "Safely knocks down old buildings", "bld3 saf2 mec1", 2, "s"],
  ["Cabinet Maker", "Builds fine wooden cabinets and furniture", "bld3 art2", 3, "s"],
  ["LEGO Master Builder", "Builds amazing models with LEGO bricks", "bld3 art3", 0, "s"],

  // More machines and vehicles
  ["Bus Driver", "Drives people safely around town", "mec3 car2", 0, "c"],
  ["Taxi Driver", "Drives people where they need to go", "mec3 adv1 car1", 0, "c"],
  ["Delivery Driver", "Delivers packages to homes", "mec3 adv1", 0, "c"],
  ["Helicopter Pilot", "Flies helicopters for tours, news and rescues", "spc3 mec3 adv1", 3, "s"],
  ["Race Car Engineer", "Tunes race cars so they go faster", "mec3 bld2 spo1", 4, "s"],
  ["Motorcycle Mechanic", "Fixes motorbikes", "mec3", 2, "s"],
  ["Bicycle Mechanic", "Fixes and builds bikes", "mec3 spo1", 0, "s"],
  ["Boat Mechanic", "Fixes boat engines", "mec3 adv1", 2, "s"],
  ["Forklift Operator", "Moves heavy boxes around warehouses", "mec3", 0, "c"],
  ["Machinist", "Uses big machines to cut metal into parts", "mec3 bld2", 2, "c"],
  ["Mechatronics Technician", "Fixes machines that mix electronics and moving parts", "mec3 tec2", 2, "g"],
  ["Railway Engineer", "Designs and looks after train tracks", "mec3 bld3", 4, "s"],
  ["Automotive Engineer", "Designs new cars", "mec3 bld2 sci1", 4, "s"],
  ["Tow Truck Driver", "Rescues broken-down cars", "mec3 saf1 car1", 0, "s"],
  ["Marine Engineer", "Designs and runs ship engines", "mec3 bld2 adv1", 4, "s"],
  ["Harbor Pilot", "Guides giant ships safely into port", "mec3 adv2 saf1", 4, "s"],
  ["Watchmaker", "Builds and fixes tiny watch parts", "mec3 art2", 2, "s"],
  ["Zamboni Driver", "Drives the ice-cleaning machine at skating rinks", "mec3 spo2", 0, "s"],
  ["Ride Operator", "Runs the rides at theme parks", "mec3 saf2", 0, "s"],
  ["Pool Technician", "Keeps swimming pools clean and safe", "mec3 saf1", 0, "s"],
  ["Printing Press Operator", "Runs machines that print books and posters", "mec3 art1", 1, "c"],

  // More space and flight
  ["Flight Instructor", "Teaches people to fly planes", "spc3 tea2 mec1", 3, "s"],
  ["Astrophysicist", "Studies how stars and black holes work", "spc3 sci3", 9, "s"],
  ["Planetary Scientist", "Studies planets and moons", "spc3 sci3", 9, "g"],
  ["Rocket Scientist", "Designs rocket engines", "spc3 bld2 sci2", 6, "g"],
  ["Satellite Engineer", "Builds satellites that orbit Earth", "spc3 tec2 bld2", 4, "g"],
  ["Mission Controller", "Guides space missions from the ground", "spc3 tec2 lea1", 4, "s"],
  ["Planetarium Presenter", "Shows people the night sky in a dome theater", "spc3 tea2 prf1", 4, "s"],
  ["Fighter Pilot", "Flies fast jets for the air force", "spc3 mec2 saf2", 4, "s"],
  ["Hot Air Balloon Pilot", "Flies balloons high over the land", "spc3 adv2", 1, "s"],
  ["Airport Manager", "Runs everything at an airport", "lea3 spc2 biz1", 4, "s"],
  ["Drone Racer", "Races tiny fast drones through obstacle courses", "spc3 tec2 spo2", 0, "g"],

  // More art and design
  ["Fashion Stylist", "Picks outfits for people and photo shoots", "art3 biz1", 1, "s"],
  ["Textile Designer", "Designs patterns for fabrics", "art3", 4, "s"],
  ["Costume Designer", "Designs costumes for plays and movies", "art3 prf2 mda1", 4, "s"],
  ["Art Teacher", "Teaches kids to draw and paint", "art3 tea3", 4, "s"],
  ["Art Therapist", "Uses art to help people feel better", "art3 car2 hlp1", 6, "g"],
  ["Calligrapher", "Writes beautiful fancy letters", "art3 wrd2", 0, "s"],
  ["Glassblower", "Shapes melted glass into art", "art3 bld1", 1, "s"],
  ["Muralist", "Paints giant pictures on walls", "art3 bld1", 0, "s"],
  ["Street Artist", "Makes art on streets and walls where it's allowed", "art3 adv1", 0, "s"],
  ["Concept Artist", "Draws ideas for movies and games before they're made", "art3 mda2", 4, "g"],
  ["Character Designer", "Invents how cartoon and game characters look", "art3 mda2", 4, "g"],
  ["Storyboard Artist", "Draws a movie scene by scene before filming", "art3 mda2 wrd1", 4, "s"],
  ["Art Director", "Leads the look of a magazine, ad or movie", "art3 lea2 mda1", 6, "s"],
  ["Furniture Designer", "Designs chairs, tables and sofas", "art3 bld2", 4, "s"],
  ["Shoe Designer", "Designs sneakers and shoes", "art3 spo1 biz1", 4, "s"],
  ["Nail Artist", "Paints tiny designs on nails", "art3 biz1", 1, "s"],
  ["Wedding Photographer", "Takes photos at weddings", "art3 mda2 car1", 1, "s"],
  ["Fashion Model", "Wears clothes for photo shoots and runway shows", "prf3 art2", 0, "s"],
  ["Gallery Owner", "Sells art in a gallery", "art3 biz3", 0, "s"],
  ["Printmaker", "Makes art prints with ink and stamps", "art3", 0, "s"],
  ["Balloon Artist", "Twists balloons into animals and shapes", "art3 prf1", 0, "s"],
  ["Face Painter", "Paints faces at parties and festivals", "art3 car1", 0, "s"],
  ["Tailor", "Sews and fixes clothes so they fit perfectly", "art3 bld1", 1, "s"],
  ["Shoemaker", "Makes and repairs shoes", "art3 bld2", 1, "s"],
  ["Blacksmith", "Hammers hot metal into tools and art", "bld3 art2", 1, "s"],
  ["Upholsterer", "Covers sofas and chairs in new fabric", "art3 bld2", 1, "s"],
  ["Sign Maker", "Designs and builds signs for shops", "art3 bld2", 1, "s"],
  ["Theme Park Designer", "Designs rides and whole theme parks", "art3 bld2 adv1", 4, "s"],
  ["Advertising Designer", "Creates ads for TV and online", "art3 mda2 biz1", 4, "c"],
  ["Medical Illustrator", "Draws the human body for medical books", "art3 hlp2 sci1", 6, "s"],

  // More food
  ["Butcher", "Cuts and prepares meat", "fod3 biz1", 1, "s"],
  ["Barista", "Makes coffee and drinks in a café", "fod3 car1", 0, "c"],
  ["Cake Designer", "Makes amazing decorated cakes", "fod3 art3", 1, "s"],
  ["Sushi Chef", "Makes sushi", "fod3 art1", 2, "s"],
  ["Pizza Chef", "Makes pizza in a hot oven", "fod3", 0, "s"],
  ["Ice Cream Maker", "Invents and makes ice cream flavors", "fod3 biz1 sci1", 0, "s"],
  ["School Cook", "Makes lunches for school kids", "fod3 car2", 0, "s"],
  ["Caterer", "Cooks food for parties and weddings", "fod3 biz2", 1, "s"],
  ["Candy Maker", "Makes sweets and candy", "fod3 art1", 0, "s"],
  ["Food Stylist", "Makes food look perfect for photos", "fod3 art2 mda1", 1, "s"],
  ["Food Photographer", "Photographs food for menus and cookbooks", "mda3 fod2 art1", 1, "s"],
  ["Recipe Developer", "Invents and tests new recipes", "fod3 wrd1 sci1", 1, "s"],
  ["Cookbook Author", "Writes cookbooks", "fod3 wrd3", 0, "s"],
  ["Cheese Maker", "Makes cheese on a farm", "fod3 ani1 sci1", 1, "s"],
  ["Orchard Farmer", "Grows apples, oranges and other fruit", "nat3 fod2", 0, "s"],
  ["Restaurant Manager", "Runs the dining room and the team", "biz3 fod2 lea1", 2, "s"],
  ["Private Chef", "Cooks for one family in their home", "fod3 car1", 2, "s"],
  ["Food Safety Inspector", "Checks that kitchens are clean and safe", "fod3 saf2 sci1", 4, "s"],
  ["Pet Food Scientist", "Makes healthy food for pets", "ani3 fod2 sci1", 4, "s"],

  // More performing
  ["Opera Singer", "Sings in operas", "prf3", 4, "s"],
  ["Orchestra Conductor", "Leads an orchestra", "prf3 lea3", 6, "s"],
  ["Choir Director", "Leads a choir", "prf3 tea2 lea1", 4, "s"],
  ["Guitarist", "Plays guitar in bands and studios", "prf3", 0, "s"],
  ["Pianist", "Plays piano at concerts", "prf3", 4, "s"],
  ["Violinist", "Plays violin in orchestras", "prf3", 4, "s"],
  ["Rapper", "Writes and performs rap songs", "prf3 wrd2", 0, "s"],
  ["Ballet Dancer", "Dances ballet on stage", "prf3 spo2", 0, "s"],
  ["Choreographer", "Makes up dances for shows and videos", "prf3 spo2 art1", 2, "s"],
  ["Puppeteer", "Brings puppets to life in shows", "prf3 art2", 0, "s"],
  ["Clown", "Makes people laugh at circuses and parties", "prf3 car1", 0, "s"],
  ["Theater Director", "Leads the team putting on a play", "prf3 lea2 wrd1", 4, "s"],
  ["Stage Manager", "Keeps a live show running smoothly backstage", "prf3 lea2", 2, "s"],
  ["Lighting Designer", "Designs the lights for shows and concerts", "prf3 tec2 art1", 2, "s"],
  ["Music Therapist", "Uses music to help people feel better", "prf3 car2 hlp1", 6, "g"],
  ["Band Manager", "Books shows and runs the business side of a band", "biz3 prf2", 0, "s"],
  ["Talent Agent", "Finds jobs for actors and musicians", "biz3 prf2", 2, "s"],
  ["Instrument Maker", "Builds guitars, violins and drums", "bld3 prf2 art1", 2, "s"],
  ["Piano Tuner", "Tunes and fixes pianos", "prf3 mec2", 1, "s"],
  ["Street Performer", "Performs for crowds on the street", "prf3 adv1", 0, "s"],
  ["Mascot Performer", "Wears a big costume and cheers at games", "prf3 spo2", 0, "s"],

  // More media and games
  ["Movie Producer", "Finds the money and people to make a movie", "mda3 biz2 lea2", 4, "s"],
  ["Special Effects Artist", "Makes explosions, monsters and magic for movies", "mda3 art2 tec2", 2, "g"],
  ["News Reporter", "Goes where the news happens and reports it", "mda3 wrd2 adv1", 4, "c"],
  ["Weather Presenter", "Presents the weather forecast on TV", "mda3 sci2", 4, "s"],
  ["Sports Journalist", "Writes and reports about sports", "spo3 wrd2 mda2", 4, "s"],
  ["Photojournalist", "Tells news stories with photos", "mda3 adv2 wrd1", 4, "s"],
  ["Stop-Motion Animator", "Makes movies by moving clay figures one frame at a time", "mda3 art3", 2, "s"],
  ["Streamer", "Plays games live for an online audience", "mda3 prf2 tec1", 0, "g"],
  ["Influencer", "Shares their life and favourite products online", "mda3 biz2", 0, "c"],
  ["Casting Director", "Chooses the actors for movies and shows", "mda3 lea2 prf1", 4, "s"],
  ["Film Critic", "Watches movies and reviews them", "mda3 wrd2", 0, "s"],
  ["Level Designer", "Builds the worlds and levels in video games", "mda3 art2 tec2", 4, "g"],
  ["Game Artist", "Draws the art for video games", "art3 mda2", 4, "g"],
  ["Game Writer", "Writes the stories and characters for video games", "wrd3 mda2", 4, "s"],
  ["Sound Designer", "Makes sound effects for movies and games", "mda3 prf2 tec1", 2, "s"],
  ["Talk Show Host", "Hosts a show and interviews guests", "mda3 prf2 wrd1", 0, "s"],
  ["Cinematographer", "Decides how every shot in a movie looks", "mda3 art2", 4, "s"],
  ["Broadcast Technician", "Keeps TV and radio signals running", "mda3 tec2 mec1", 2, "c"],
  ["Public Relations Specialist", "Helps companies share good news with the public", "biz3 mda2 wrd1", 4, "s"],
  ["Esports Coach", "Coaches video game teams", "mda3 tea2 spo1", 0, "g"],
  ["Travel Vlogger", "Films trips around the world for an online channel", "adv3 mda3", 0, "g"],
  ["Foreign Correspondent", "Reports the news from other countries", "mda3 adv3 wrd2", 4, "s"],

  // More words
  ["Novelist", "Writes long stories", "wrd3 art1", 0, "c"],
  ["Comic Book Writer", "Writes the stories for comics", "wrd3 art2", 0, "s"],
  ["Speechwriter", "Writes speeches for leaders", "wrd3 lea2", 4, "s"],
  ["Proofreader", "Finds spelling and grammar mistakes", "wrd3", 2, "c"],
  ["Publisher", "Chooses which books get printed and sold", "wrd3 biz2", 4, "s"],
  ["Bookseller", "Runs a bookshop and recommends books", "wrd3 biz2", 0, "s"],
  ["Blogger", "Writes posts online about things they love", "wrd3 mda2", 0, "c"],
  ["Interpreter", "Translates what people say out loud, as they speak", "wrd3 adv2 car1", 4, "s"],
  ["Linguist", "Studies how languages work", "wrd3 sci2", 6, "s"],
  ["Archivist", "Looks after old documents and records", "wrd3 sci1", 6, "s"],
  ["Storyteller", "Tells stories to audiences at libraries and festivals", "wrd3 prf2 tea1", 0, "s"],
  ["Puzzle Maker", "Makes crosswords and word puzzles for newspapers and apps", "wrd3 art1", 0, "s"],
  ["Greeting Card Writer", "Writes the words inside greeting cards", "wrd3 art1", 0, "s"],
  ["Magazine Editor", "Chooses the stories for a magazine", "wrd3 lea2 art1", 4, "c"],
  ["Genealogist", "Traces family trees back through history", "wrd3 sci1", 4, "s"],
  ["Court Reporter", "Types every word said in court", "wrd3 lea1", 2, "c"],

  // More teaching
  ["Math Teacher", "Helps students love numbers", "tea3 sci2", 4, "s"],
  ["English Teacher", "Teaches reading and writing", "tea3 wrd3", 4, "s"],
  ["History Teacher", "Teaches about the past", "tea3 wrd2", 4, "s"],
  ["Special Education Teacher", "Teaches kids who learn in different ways", "tea3 car3", 4, "g"],
  ["Preschool Teacher", "Teaches the youngest kids through play", "tea3 car2 art1", 2, "s"],
  ["Teaching Assistant", "Helps the teacher and supports kids in class", "tea3 car2", 1, "s"],
  ["Driving Instructor", "Teaches people to drive", "tea3 mec2 saf1", 1, "c"],
  ["Swimming Teacher", "Teaches kids to swim", "tea3 spo2 saf1", 1, "s"],
  ["Dance Teacher", "Teaches dance classes", "tea3 prf2 spo1", 1, "s"],
  ["Coding Teacher", "Teaches kids to write code", "tea3 tec2", 4, "g"],
  ["Online Course Creator", "Makes video lessons people learn from online", "tea3 mda2", 0, "g"],
  ["Education Researcher", "Studies how kids learn best", "tea3 sci2", 8, "s"],
  ["Museum Educator", "Runs fun learning activities at museums", "tea3 art1 sci1", 4, "s"],
  ["Camp Counselor", "Looks after kids at summer camp", "tea3 car2 adv1", 0, "s"],
  ["Nanny", "Looks after children in their home", "car3 tea2", 0, "s"],
  ["Babysitter", "Looks after kids while their parents are out", "car3 tea1", 0, "s"],

  // More health
  ["Pediatric Nurse", "Cares for sick children in hospital", "hlp3 car2", 4, "g"],
  ["Emergency Doctor", "Treats patients who rush into the emergency room", "hlp3 saf2 sci1", 11, "g"],
  ["Anesthesiologist", "Puts patients safely to sleep for surgery", "hlp3 sci2", 12, "s"],
  ["Cardiologist", "Heart doctor", "hlp3 sci2", 12, "g"],
  ["Dermatologist", "Skin doctor", "hlp3 sci2", 11, "s"],
  ["Radiologist", "Reads X-rays and scans to find problems", "hlp3 tec2 sci1", 12, "c"],
  ["X-Ray Technician", "Takes X-rays and scans of patients", "hlp3 tec2", 2, "s"],
  ["Dental Hygienist", "Cleans teeth and teaches healthy brushing", "hlp3 car1", 2, "g"],
  ["Orthodontist", "Straightens teeth with braces", "hlp3 art1", 10, "s"],
  ["Chiropractor", "Helps people with back and joint pain", "hlp3 spo1", 7, "s"],
  ["Occupational Therapist", "Helps people do everyday things again after an injury or illness", "hlp3 car2", 6, "g"],
  ["Audiologist", "Tests hearing and fits hearing aids", "hlp3 sci2", 8, "s"],
  ["Medical Researcher", "Searches for cures for diseases", "sci3 hlp3", 9, "g"],
  ["Pharmacy Technician", "Helps the pharmacist prepare medicines", "hlp3 sci1", 1, "c"],
  ["Medical Lab Scientist", "Tests blood and samples to help doctors", "sci3 hlp2", 4, "s"],
  ["Home Health Aide", "Cares for sick or older people at home", "car3 hlp2", 0, "g"],
  ["School Nurse", "Looks after kids who feel sick at school", "hlp3 car2 tea1", 4, "s"],
  ["Psychiatrist", "Doctor who helps people with their mental health", "hlp3 car2 sci1", 12, "g"],
  ["Therapist", "Helps people talk through their feelings and problems", "car3 hlp2", 6, "g"],
  ["Massage Therapist", "Helps sore muscles relax", "hlp3 spo1", 1, "s"],
  ["Athletic Trainer", "Helps athletes avoid and recover from injuries", "spo3 hlp3", 4, "g"],
  ["Prosthetist", "Makes artificial arms and legs", "hlp3 bld2 tec1", 6, "g"],
  ["Hospital Administrator", "Runs a hospital", "lea3 hlp2 biz1", 6, "s"],
  ["Public Health Worker", "Helps whole communities stay healthy", "hlp3 car2 sci1", 4, "g"],

  // More caring and community
  ["Child Care Worker", "Looks after young children at a daycare", "car3 tea2", 1, "s"],
  ["Community Organizer", "Brings neighbors together to fix problems", "car3 lea2", 2, "s"],
  ["Charity Director", "Leads a charity that helps people", "car3 lea3 biz1", 4, "s"],
  ["Life Coach", "Helps people reach their goals", "car3 tea1 biz1", 1, "s"],
  ["Family Therapist", "Helps families get along", "car3 hlp2", 6, "s"],
  ["Refugee Support Worker", "Helps families who had to leave their countries", "car3 adv2 wrd1", 4, "s"],
  ["Faith Leader", "Supports people with faith and comfort", "car3 lea1 wrd1", 4, "s"],
  ["Funeral Director", "Helps families say goodbye to loved ones", "car3 biz1", 2, "s"],
  ["Receptionist", "Welcomes visitors and answers calls", "car3 biz1", 0, "c"],
  ["Customer Service Representative", "Helps customers with questions and problems", "car3 biz2", 0, "c"],
  ["Concierge", "Helps hotel guests with anything they need", "car3 adv2", 0, "s"],
  ["Wedding Planner", "Plans perfect weddings", "biz3 car2 art1", 1, "s"],
  ["Personal Assistant", "Helps a busy person stay organized", "biz3 car2", 0, "c"],
  ["Volunteer Coordinator", "Organizes volunteers to help with projects", "car3 lea2", 2, "s"],
  ["Victim Advocate", "Supports people who have been hurt by crime", "car3 lea2 saf1", 4, "s"],
  ["Mail Carrier", "Delivers letters and packages to every home", "car2 mec2 adv1", 0, "c"],
  ["Janitor", "Keeps schools and buildings clean", "car2 bld2", 0, "s"],
  ["House Cleaner", "Makes homes sparkling clean", "car3", 0, "c"],
  ["Mover", "Packs and carries furniture to people's new homes", "spo3 car1", 0, "s"],

  // More safety
  ["Security Guard", "Watches over buildings and keeps them safe", "saf3", 0, "c"],
  ["Border Patrol Agent", "Protects a country's borders", "saf3 adv2", 1, "s"],
  ["FBI Agent", "Investigates big crimes and catches criminals", "saf3 lea2 sci1", 6, "s"],
  ["Crime Scene Investigator", "Collects clues at crime scenes", "saf3 sci3", 4, "s"],
  ["Bomb Disposal Expert", "Safely removes dangerous explosives", "saf3 mec2 sci1", 3, "s"],
  ["Smokejumper", "Parachutes in to fight wildfires", "saf3 adv2 spo2", 2, "s"],
  ["Ski Patroller", "Rescues skiers on the mountain", "saf3 spo2 adv1", 1, "s"],
  ["Navy Sailor", "Serves on navy ships", "saf3 adv2 mec1", 0, "s"],
  ["Rescue Diver", "Dives underwater to rescue people", "saf3 spo2 adv2", 2, "s"],
  ["Emergency Manager", "Plans how a city handles disasters", "saf3 lea3", 4, "g"],
  ["Fire Inspector", "Checks buildings for fire dangers", "saf3 bld2", 2, "s"],
  ["Bodyguard", "Protects famous people", "saf3 spo2", 1, "s"],
  ["Private Investigator", "Solves mysteries for people who hire them", "saf3 sci1 wrd1", 2, "s"],
  ["Prison Officer", "Keeps prisons safe and orderly", "saf3 lea1", 1, "s"],
  ["K-9 Police Officer", "Works with a police dog to keep people safe", "saf3 ani3", 2, "s"],
  ["Search Dog Handler", "Trains dogs to find lost people", "ani3 saf3", 2, "s"],
  ["Wildland Firefighter", "Fights forest fires", "saf3 nat2 spo2", 1, "s"],
  ["Pest Control Technician", "Gets rid of bugs and mice safely", "saf3 ani2", 1, "s"],
  ["Lighthouse Keeper", "Looks after a lighthouse by the sea", "adv3 saf1 mec1", 0, "c"],
  ["Skyscraper Window Cleaner", "Cleans windows high up on skyscrapers", "adv3 saf2", 0, "c"],

  // More leading and law
  ["President / Prime Minister", "Leads a whole country", "lea3 car1 prf1", 10, "s"],
  ["Senator / Member of Parliament", "Makes laws for the country", "lea3 wrd2 car1", 6, "s"],
  ["Ambassador", "Represents their country in another country", "lea3 adv3", 8, "s"],
  ["Paralegal", "Helps lawyers get ready for court", "lea3 wrd2", 2, "c"],
  ["Police Chief", "Leads the police in a city", "saf3 lea3", 10, "s"],
  ["Union Leader", "Speaks up for workers' rights", "lea3 car2", 4, "s"],
  ["Human Rights Lawyer", "Fights for people's rights in court", "lea3 car3 wrd1", 7, "s"],
  ["Environmental Lawyer", "Uses the law to protect nature", "lea3 nat2", 7, "g"],
  ["Mediator", "Helps people end arguments fairly", "lea3 car2", 4, "s"],
  ["Office Manager", "Leads a team at work and keeps things running", "lea3 biz2", 2, "s"],
  ["Military Officer", "Leads soldiers", "saf3 lea3", 4, "s"],
  ["City Council Member", "Helps make decisions for a town", "lea3 car2", 4, "s"],
  ["Campaign Manager", "Runs election campaigns", "lea3 biz2 mda1", 4, "s"],
  ["Patent Lawyer", "Protects inventors' ideas", "lea3 sci2", 9, "s"],

  // More business
  ["Cashier", "Rings up what people buy at a store", "biz3 car1", 0, "c"],
  ["Bank Teller", "Helps customers at the bank", "biz3 car1", 0, "c"],
  ["Insurance Agent", "Helps people protect their homes, cars and health", "biz3 car1", 2, "c"],
  ["Auditor", "Checks that a company's money records are correct", "biz3 sci1", 4, "c"],
  ["Actuary", "Uses math to predict risks", "biz3 sci3", 6, "g"],
  ["Investment Banker", "Helps companies raise big amounts of money", "biz3 lea1", 6, "s"],
  ["Tax Advisor", "Helps people pay the right taxes", "biz3 car1", 4, "c"],
  ["Store Buyer", "Chooses what products a store sells", "biz3 art1", 4, "s"],
  ["Online Store Owner", "Sells products on the internet", "biz3 tec2", 0, "g"],
  ["Business Analyst", "Finds ways for companies to work better", "biz3 tec1 sci1", 4, "g"],
  ["Management Consultant", "Gives companies advice to fix problems", "biz3 lea2", 4, "s"],
  ["Warehouse Manager", "Runs a big warehouse", "biz3 lea2 mec1", 2, "c"],
  ["Toy Store Owner", "Runs a shop full of toys", "biz3 car1", 0, "s"],
  ["Car Salesperson", "Sells new and used cars", "biz3 mec2", 0, "c"],
  ["Antique Dealer", "Buys and sells old treasures", "biz3 art2 wrd1", 0, "s"],
  ["Auctioneer", "Sells things super fast at auctions", "biz3 prf2", 1, "s"],
  ["Fundraiser", "Raises money for good causes", "biz3 car2", 2, "s"],
  ["Advertising Executive", "Runs ad campaigns for brands", "biz3 mda2 art1", 4, "s"],
  ["Recruiter", "Finds the right people for jobs", "biz3 car2", 2, "c"],
  ["Venture Capitalist", "Invests in new startup companies", "biz3 tec1", 6, "s"],
  ["Travel Agent", "Plans trips for people", "adv3 biz2", 1, "c"],

  // More nature
  ["Arborist", "Climbs and cares for trees", "nat3 spo1", 2, "s"],
  ["Conservationist", "Protects wild places and animals", "nat3 ani2", 4, "g"],
  ["Soil Scientist", "Studies dirt to help farms grow food", "nat3 sci2", 4, "s"],
  ["Horticulturist", "Grows and studies plants and flowers", "nat3 sci1", 4, "s"],
  ["Greenhouse Grower", "Grows plants in glass houses", "nat3 fod1", 0, "s"],
  ["Recycling Coordinator", "Runs recycling programs", "nat3 car1", 2, "g"],
  ["Renewable Energy Engineer", "Designs wind and solar power", "nat3 bld3 sci1", 4, "g"],
  ["Water Treatment Operator", "Makes water clean and safe to drink", "nat3 sci1 saf1", 1, "s"],
  ["Glaciologist", "Studies glaciers and ice", "sci3 nat2 adv2", 6, "s"],
  ["Marine Conservationist", "Protects oceans and sea life", "nat3 ani2 adv1", 4, "g"],
  ["Nature Guide", "Leads nature walks and teaches about plants and animals", "nat3 tea2 adv1", 0, "s"],
  ["Organic Farmer", "Grows food without chemicals", "nat3 fod2", 0, "s"],
  ["Tree Planter", "Plants thousands of trees", "nat3 spo1", 0, "s"],
  ["Sustainability Manager", "Helps companies be kinder to the planet", "nat3 biz2", 4, "g"],
  ["Groundskeeper", "Takes care of parks and sports fields", "nat3 spo2", 0, "s"],

  // More animals
  ["Animal Behaviorist", "Studies why animals act the way they do", "ani3 sci2", 6, "s"],
  ["Marine Mammal Trainer", "Trains dolphins and sea lions", "ani3 tea2", 2, "s"],
  ["Aquarist", "Cares for fish at an aquarium", "ani3 nat1", 2, "s"],
  ["Wildlife Rehabilitator", "Nurses hurt wild animals back to health", "ani3 hlp2", 2, "s"],
  ["Veterinary Surgeon", "Does operations on animals", "ani3 hlp3", 10, "s"],
  ["Exotic Animal Vet", "Cares for reptiles, birds and unusual pets", "ani3 hlp3", 9, "s"],
  ["Dog Walker / Pet Sitter", "Looks after pets while their owners are away", "ani3 car1", 0, "s"],
  ["Pet Store Owner", "Runs a shop for pets", "ani3 biz3", 0, "s"],
  ["Farrier", "Puts shoes on horses", "ani3 mec1", 2, "s"],
  ["Jockey", "Rides racehorses", "ani3 spo3", 0, "s"],
  ["Guide Dog Trainer", "Trains dogs to help blind people", "ani3 car2 tea1", 2, "s"],
  ["Ornithologist", "Studies birds", "ani3 sci2", 6, "s"],
  ["Herpetologist", "Studies snakes, lizards and frogs", "ani3 sci2", 6, "s"],
  ["Primatologist", "Studies monkeys and apes", "ani3 sci2 adv1", 8, "s"],
  ["Animal Shelter Manager", "Runs a shelter for lost animals", "ani3 lea2 car1", 2, "s"],
  ["Dairy Farmer", "Raises cows for milk", "ani3 nat2", 0, "c"],
  ["Rancher", "Raises cattle on a big ranch", "ani3 nat2 biz1", 0, "c"],
  ["Shark Researcher", "Studies sharks in the ocean", "ani3 sci2 adv2", 6, "s"],
  ["Zoo Vet", "Takes care of zoo animals when they are sick", "ani3 hlp3", 9, "s"],
  ["Safari Guide", "Takes visitors to see wild animals", "adv3 ani3", 1, "s"],

  // More sports
  ["Soccer Player", "Plays professional soccer", "spo3", 0, "s"],
  ["Basketball Player", "Plays professional basketball", "spo3", 0, "s"],
  ["Football Player", "Plays professional football", "spo3", 0, "s"],
  ["Baseball Player", "Plays professional baseball", "spo3", 0, "s"],
  ["Hockey Player", "Plays professional ice hockey", "spo3", 0, "s"],
  ["Tennis Player", "Plays tennis in tournaments", "spo3", 0, "s"],
  ["Swimmer", "Races in swimming competitions", "spo3", 0, "s"],
  ["Gymnast", "Competes in gymnastics", "spo3 prf1", 0, "s"],
  ["Skateboarder", "Does skateboard tricks in competitions", "spo3 adv1", 0, "s"],
  ["Surf Instructor", "Surfs big waves and teaches others", "spo3 adv2 tea1", 0, "s"],
  ["Cyclist", "Races bikes", "spo3 adv1", 0, "s"],
  ["Golfer", "Plays golf in tournaments", "spo3", 0, "s"],
  ["Boxer", "Competes in boxing", "spo3", 0, "s"],
  ["Figure Skater", "Skates and spins on ice", "spo3 prf2", 0, "s"],
  ["Sports Agent", "Gets deals for athletes", "biz3 spo2", 4, "s"],
  ["Sports Team Manager", "Runs a sports team", "spo3 lea3 biz1", 4, "s"],
  ["Sports Photographer", "Photographs athletes in action", "spo3 mda2 art1", 1, "s"],
  ["Fitness Instructor", "Leads exercise classes", "spo3 hlp1 tea1", 1, "g"],
  ["Sports Psychologist", "Helps athletes stay confident", "spo3 car2 hlp1", 8, "s"],
  ["Rock Climbing Instructor", "Teaches climbing", "spo3 adv2 tea1", 1, "s"],
  ["Sports Equipment Designer", "Designs balls, bats and gear", "spo3 bld2 art1", 4, "s"],
  ["Olympic Athlete", "Competes for their country at the Olympics", "spo3 adv1", 0, "s"],

  // More adventure
  ["Cruise Director", "Plans the fun on cruise ships", "adv3 prf2 car1", 1, "s"],
  ["Deep-Sea Explorer", "Explores the deepest parts of the ocean", "adv3 sci2 mec1", 6, "s"],
  ["Polar Researcher", "Does science in the Arctic and Antarctic", "sci3 adv3", 6, "s"],
  ["Cave Explorer", "Explores underground caves", "adv3 sci1 spo1", 0, "s"],
  ["Travel Photographer", "Photographs places around the world", "adv3 art2 mda1", 1, "s"],
  ["Adventure Tour Leader", "Leads kayaking, hiking and climbing trips", "adv3 spo2 lea1", 1, "s"],
  ["Sailor", "Sails boats across the sea", "adv3 mec2", 1, "s"],
  ["Shipwreck Diver", "Searches for sunken ships and treasure", "adv3 sci1 spo1", 1, "s"],
  ["International Aid Worker", "Helps people in other countries after disasters", "car3 adv3", 4, "s"],
  ["Expedition Doctor", "Looks after explorers on big trips", "hlp3 adv3", 8, "s"],

  // More future jobs
  ["Prompt Engineer", "Writes instructions that get the best work from AI", "tec3 wrd2", 2, "f"],
  ["AI Ethics Advisor", "Makes sure AI is fair and safe", "tec3 lea2 car1", 6, "f"],
  ["Home Robot Designer", "Designs robots that help families at home", "bld3 tec3", 4, "f"],
  ["Space Hotel Manager", "Runs a hotel in orbit around Earth", "spc3 biz2 car1", 4, "f"],
  ["Asteroid Miner", "Collects metals from asteroids", "spc3 mec2 bld1", 6, "f"],
  ["Space Lawyer", "Makes the rules for who can use space", "lea3 spc2", 7, "f"],
  ["Carbon Capture Technician", "Runs machines that pull pollution out of the air", "nat3 mec2", 2, "f"],
  ["Underwater City Builder", "Builds homes under the sea", "bld3 adv2", 6, "f"],
  ["Hologram Designer", "Creates 3D holograms for shows and calls", "mda3 tec2 art1", 4, "f"],
  ["Brain-Computer Engineer", "Builds devices that connect brains to computers", "tec3 hlp2 sci2", 8, "f"],
  ["Robot Trainer", "Teaches home robots new jobs", "tec3 tea2", 1, "f"],
  ["Vertical Farmer", "Grows food in tall indoor farms", "nat3 tec2 fod1", 2, "f"],
  ["Augmented Reality Designer", "Designs digital things you see through special glasses", "art3 tec2", 4, "f"],
  ["Wildlife DNA Detective", "Uses DNA to protect endangered animals", "ani3 sci3", 6, "f"],
  ["Remote Ship Captain", "Runs self-driving ships from the shore", "mec3 tec2 adv1", 4, "f"],
  ["Flying Car Mechanic", "Fixes flying taxis", "mec3 spc2", 2, "f"],
  ["Metaverse Architect", "Designs buildings in virtual worlds", "bld3 art2 tec2", 4, "f"],
  ["Climate Relocation Planner", "Helps people move away from rising seas", "car3 lea2 nat1", 6, "f"],
  ["Moon Base Doctor", "Takes care of people living on the moon", "hlp3 spc3", 10, "f"],
  ["Digital Balance Coach", "Helps people balance screens and real life", "car3 hlp1 tec1", 2, "f"],
  ["Synthetic Biologist", "Designs new living cells to make medicines", "sci3 hlp2", 8, "f"],
  ["Crop Designer", "Designs crops that grow in tough weather", "nat3 sci3 fod1", 6, "f"],
];
