// Future Map — 200 extra opening questions.
// They come in 40 sets of 5. Each set covers all 20 topics exactly once, so any
// 2 sets give a fair start (every topic offered twice). Each run of the survey
// picks 2 random sets, so the questions are different almost every time.
//
// Format: "Question|topic emoji answer|topic emoji answer|..."

const QUESTION_SETS_TEXT = [
  [ "You're in charge of the class party. What's your job?|lea 📋 Be the boss of the planning|biz 💵 Collect money for snacks|fod 🍰 Bake the cake|wrd ✉️ Write the invitations",
    "Pick a new toy.|ani 🐹 A pet hamster|bld 🧱 A giant building set|tec 🤖 A robot you can program|nat 🌱 A grow-your-own plant kit",
    "Which camp would you go to?|hlp 🩹 Junior doctor camp|prf 🎤 Singing camp|adv 🏕️ Wilderness camp|saf 🚒 Junior firefighter camp",
    "What would you do at school all day if you could?|tea 🧑‍🏫 Be the teacher for a day|spc 🪐 Learn about planets|mda 🎬 Make a class movie|car 🤝 Help kids who need a friend",
    "Pick a fun Saturday morning.|mec 🔧 Fix up an old go-kart|art 🎨 Paint a picture|spo 🏀 Shoot hoops|sci 🧪 Do a slime experiment" ],
  [ "What would your how-to video be about?|tea 📚 How to do a tricky math problem|art 🖌️ How to draw animals|tec 💻 How to code a game|saf 🦺 How to stay safe in a storm",
    "Pick a book to read.|sci 🔬 A book of wild experiments|prf 🎸 A story about a rock band|spc 🚀 A book about astronauts|wrd 📖 A giant book of fairy tales",
    "You found a treasure map! What do you do?|adv 🗺️ Go find the treasure|biz 💰 Plan what to buy with the treasure|lea 🧭 Get a team together and lead it|nat 🌲 Explore the forest on the way",
    "Pick your part in a school assembly.|mda 📺 Film it for the school channel|spo 🏃 Run the sports demo|hlp 🍎 Talk about staying healthy|bld 🛠️ Build the stage",
    "Your family is having a big picnic. You…|mec 🚗 Help pack and fix the wagon|ani 🐕 Look after the dog|fod 🥪 Make all the sandwiches|car 👵 Make sure grandma is comfy" ],
  [ "Which would you most like to build?|tec 📱 A phone app|mec 🏎️ A go-kart|bld 🏠 A doghouse|spc 🚀 A model rocket that really flies",
    "Pick something to do outside.|nat 🌼 Plant flowers|car 🧹 Help clean up the neighborhood|prf 🎶 Play music in the park|art 🖍️ Draw with chalk on the sidewalk",
    "Pick a class helper badge.|tea ⭐ Reading buddy|wrd 📰 Class newspaper writer|biz 🪙 Class shop cashier|hlp 🩹 First aid helper",
    "Which would you like to try first?|fod 🍣 Making sushi|sci 🔬 Looking at pond water under a microscope|spo 🧗 Rock climbing|adv 🚣 White-water rafting",
    "Which TV show would you watch?|ani 🐼 A show about baby animals|mda 🎮 A show about making video games|lea 🏛️ A show about kids running a town|saf 🚓 A show about police and rescuers" ],
  [ "What would you do at a science fair?|sci 🧫 Show your own experiment|saf 🧯 Show how fire extinguishers work|car 🤗 Help younger kids with their projects|bld 🌉 Build a bridge from popsicle sticks",
    "At the school talent show, you would…|prf 🎤 Sing a song|lea 🎙️ Be the host who runs the show|fod 🧁 Run the bake sale|hlp 🩹 Be the first aid helper backstage",
    "It's a snow day! You…|wrd 📚 Curl up with a good book|mec 🛷 Fix up your sled so it goes faster|tea ⛄ Teach your little cousin to build a snowman|nat ❄️ Look at snowflakes and animal tracks",
    "Which would you love to see up close?|ani 🦒 A giraffe|tec 🤖 A robot factory|spc 🚀 A space shuttle|adv 🏯 An ancient castle in another country",
    "Pick a poster for your room.|art 🖼️ A famous painting|mda 🎬 Your favourite movie|spo 🏆 Your favourite sports star|biz 📈 A chart of your savings growing" ],
  [ "At a sleepover, you're the one who…|tea 📋 Teaches everyone a new game|lea 🗳️ Decides what everyone does|mec 🔦 Fixes the broken flashlight|saf 🛡️ Makes sure everyone is safe",
    "Which gift would you make for a friend?|art 🎨 A painting|wrd 📜 A poem|bld 📦 A wooden box|adv 🗺️ A map to a secret hideout",
    "Pick a helper job for a day.|ani 🐑 Feeding the animals at a farm|hlp 🏥 Helping at a children's hospital|nat 🌳 Planting trees in the park|fod 🍲 Cooking soup at a soup kitchen",
    "What would you do with a giant screen?|sci 🌌 Show amazing science facts|prf 🎤 Sing karaoke|tec 💻 Code a game to play on it|mda 🎬 Watch and review movies",
    "Your class earned a reward. You'd choose…|biz 🛍️ A class store with pretend money|car 🎁 Making gifts for a children's hospital|spc 🔭 A night of stargazing|spo ⚽ Extra-long sports time" ],
  [ "Which documentary would you watch?|spc 🚀 Journey to Mars|sci ⚗️ The world's craziest experiments|mda 🎥 How movies are made|nat 🌿 Secrets of the rainforest",
    "On a camping trip, you'd…|spo 🥾 Race everyone up the trail|lea 🧭 Lead the group|car 🍫 Share snacks and make sure everyone's happy|adv 🔦 Explore a cave",
    "You have a free hour at school. You…|ani 🐠 Look after the class fish|bld 🧩 Build something with the craft supplies|tea 📖 Read to the kindergarten class|prf 🎹 Practise piano",
    "What would you want to invent?|mec 🚗 A car that flies|tec 🧠 A robot that does homework|hlp 💊 A medicine that cures colds|biz 💸 A toy every kid wants to buy",
    "Pick a weekend class.|art 🖌️ Painting class|fod 👩‍🍳 Cooking class|wrd ✍️ Story writing class|saf 🛟 Lifesaving class at the pool" ],
  [ "Your town is having a festival. You…|prf 🎺 Play in the parade band|nat 🌸 Decorate with flowers|car 🎈 Help at the kids' tent|mec 🎡 Help run the rides",
    "If you could have any gadget…|hlp 🩺 A scanner that sees inside bodies|tec ⌚ A smartwatch you coded yourself|wrd 🗣️ A translator that speaks every language|adv 🧭 A compass that finds hidden places",
    "You get to spend a day at a…|biz 🏦 Bank vault|fod 🍫 Chocolate factory|mda 📺 TV studio|saf 🚒 Fire station",
    "Pick a club at school.|sci 🔬 Science club|ani 🐾 Animal lovers club|lea 🗳️ Student council|art 🎨 Art club",
    "What would you do in a big empty field?|bld 🏰 Build a giant fort|tea 🎯 Teach little kids a new game|spo ⚽ Play soccer|spc 🌠 Watch the stars at night" ],
  [ "Your friend is not feeling well. You…|hlp 🌡️ Take their temperature|ani 🐶 Bring your dog to cheer them up|mda 📺 Pick a funny movie to watch together|car 🍵 Bring them soup and keep them company",
    "Pick a project for Earth Day.|nat 🌱 Plant a school garden|lea 📣 Start a school recycling rule|wrd 📝 Write an article about too much trash|art 🎨 Make art from recycled stuff",
    "Which would be the coolest thing to own?|mec 🏍️ A dirt bike|bld 🔨 A workshop full of tools|biz 🏪 Your very own shop|spc 🔭 A giant telescope",
    "On a trip to a new city, you'd…|sci 🏛️ Visit the science museum|tea 🗺️ Be the tour guide for your family|fod 🥟 Try the local food|adv 🚠 Ride the cable car up the mountain",
    "What would you do at recess?|tec 🎮 Play a coding game on a tablet|prf 💃 Make up a dance|spo 🏃 Play tag|saf 🦺 Be the playground safety helper" ],
  [ "What's your dream birthday party?|spo 🏀 A sports party|ani 🐴 A pony party|biz 🎟️ A carnival where you sell the tickets|fod 🍕 A make-your-own-pizza party",
    "Which hero would you be?|hlp 🦸 A doctor who can cure anything|saf 🚁 A rescue pilot|spc 👩‍🚀 An astronaut who saves the space station|nat 🌍 A hero who saves the rainforest",
    "You're making a class website. You'd…|art 🎨 Design how it looks|tec 💻 Write the code|lea 📋 Decide what goes on it|mda 📹 Make videos for it",
    "What would you look for in a library?|bld 📐 A book on how buildings are made|wrd 📚 A new novel|car 👧 A book to help a younger kid learn|sci 🧪 A book of experiments",
    "At a school fair, you'd run…|prf 🎤 The karaoke stage|tea 🧩 A puzzle station for little kids|mec 🚗 The toy car racetrack|adv 🗺️ The treasure hunt" ],
  [ "What would you want to learn about?|spc 🌙 How the moon was made|fod 🍞 How bread rises|hlp ❤️ How the heart pumps blood|art 🎨 How famous painters made their art",
    "How would you spend time with a puppy?|ani 🐕 Brush it and feed it|tea 🦮 Teach it to sit and roll over|wrd 📝 Write a story about its adventures|spo 🏃 Take it for a run",
    "Pick a road trip activity.|mda 📸 Take photos and make a video|nat 🏞️ Stop at every national park|adv 🗺️ Pick the route on the map|mec 🔧 Help check the car's engine and tires",
    "Your neighborhood has a problem. You'd…|biz 💵 Raise money to fix it|car 🤝 Get neighbors to help each other|saf 🚸 Make the street safer for kids|bld 🛠️ Build something to fix it",
    "What would you do with a free afternoon at home?|prf 🎸 Practise guitar|tec 💻 Learn to code|sci 🔍 Look at bugs with a magnifying glass|lea 🗳️ Plan a family meeting and run it" ],
  [ "Which space job would you choose?|spc 👩‍🚀 Astronaut|fod 🍱 Space chef making astronaut food|saf 🧑‍🚒 Space station safety officer|tec 🛰️ Satellite programmer",
    "Which expedition would you join?|adv 🧊 A trip to the North Pole|sci 🦴 A dinosaur fossil dig|bld 🏗️ Building a bridge in the jungle|hlp ⛑️ Being the expedition doctor",
    "What would you customize?|mec 🚲 Your bike, with a motor|ani 🐠 A giant fish tank|art 👟 Your sneakers, with paint|biz 🏪 Your lemonade stand, to earn more",
    "At the park, you'd…|tea 🎓 Show kids how to fly a kite|nat 🦋 Look for butterflies|spo ⚾ Play baseball|lea 📣 Organize a big game for everyone",
    "Pick a way to make someone's day.|car 🤗 Give them a big hug|wrd 💌 Write them a sweet note|mda 🎥 Make a funny video for them|prf 🎶 Sing them a song" ],
  [ "Which race would you enter?|mec 🏎️ A go-kart race|spo 🏃 A running race|ani 🐎 A horse race|adv 🛶 A canoe race down a river",
    "Pick a summer job.|biz 🍋 Sell drinks at the beach|nat 🌿 Help at a garden center|sci 🔬 Help in a real science lab|tea 🏕️ Help at a kids' day camp",
    "What would you make for a contest?|art 🗿 A sculpture|tec 🤖 A robot|fod 🎂 A three-layer cake|bld 🏰 A giant LEGO castle",
    "You're on a spaceship. What's your job?|hlp 🩺 Ship's doctor|lea 👨‍✈️ Captain|car 🫂 Keeping the crew happy|spc 🧭 Navigator finding the way through space",
    "What would you like to be famous for?|mda 📺 A famous video channel|wrd 📚 A best-selling book|prf 🎤 Being a pop star|saf 🦸 Saving someone's life" ],
  [ "Pick a show to put on.|ani 🐩 A dog show|prf 🎭 A musical|bld 🏗️ A building contest|fod 🍝 A cooking show",
    "What would you do on a sunny morning?|nat 🌻 Water the garden|spo 🚴 Go for a bike ride|hlp 🩹 Help at the first aid tent at a fun run|tec 💻 Build a weather app",
    "Your class is making a newspaper. You'd…|mda 📸 Take the photos|lea 🧑‍💼 Be the editor in charge|wrd 📝 Write the stories|spc 🌙 Write the space and stars page",
    "What would you like to learn this year?|tea 🧑‍🏫 How to teach a lesson|mec 🔧 How engines work|sci ⚗️ Chemistry|saf 🚨 What to do in an emergency",
    "What would you do on vacation?|adv 🏝️ Explore a new island|biz 🛍️ Bargain at a busy market|art 🖼️ Visit art museums|car 🏘️ Help build homes for families who need them" ],
  [ "Which would you like to try?|mec 🚜 Driving a digger|tec 🕹️ Making a video game|spo 🏄 Surfing|wrd 🎙️ Interviewing someone famous",
    "Pick a cozy afternoon.|car ☕ Visiting your grandparents|art 🧶 Knitting or crafts|fod 🍪 Baking cookies|nat 🌧️ Watching the rain and listening to birds",
    "Pick a dream for when you grow up.|spc 🚀 Go to space|prf 🎤 Sing in a sold-out stadium|lea 🏛️ Lead your country|tea 🍎 Be everyone's favourite teacher",
    "Pick an afternoon activity.|biz 🏷️ Have a yard sale|mda 📹 Film a short movie|bld 🪵 Build a birdhouse|adv 🥾 Hike to a waterfall",
    "Which would you rather help with?|sci 🧪 Testing water to see if it's clean|hlp 🏥 Taking care of sick people|saf 🚒 Putting out a fire|ani 🐦 Caring for a hurt bird" ],
  [ "If you had a million dollars, you'd…|biz 📈 Start a big company|bld 🏠 Build your dream house|hlp 🏥 Build a hospital|lea 🏛️ Run for mayor",
    "Pick a morning routine.|spo 🏋️ Work out|wrd 📖 Read a chapter|nat 🌅 Walk outside and enjoy nature|saf 🚨 Test the smoke alarms at home",
    "What would you do at the county fair?|prf 🎻 Play in the talent show|art 🖼️ Enter the art contest|ani 🐓 Show your prize chicken|mec 🚜 Drive in the tractor parade",
    "Pick a fun fact to learn.|fod 🍫 How chocolate is made|spc 🌞 How hot the sun is|adv 🏔️ How people climb Mount Everest|sci ⚡ How lightning happens",
    "What would you do on a rainy day?|tea 🃏 Teach your sibling a card game|car 📞 Call a friend who's lonely|mda 🎬 Make a stop-motion movie|tec 💻 Build a website" ],
  [ "Which would you like to control?|saf 🚨 The alarms at a fire station|lea 🏛️ The rules of your town|mda 🎚️ The cameras at a TV studio|mec 🚂 A real steam train",
    "What would you like to do at the Olympics?|spo 🥇 Compete for a gold medal|hlp 🩺 Be a team doctor|prf 🎺 Perform at the opening show|art 🎨 Design the medals",
    "How would you spend a day off school?|tea 📚 Tutor a friend|car 🧺 Help at a food bank|adv 🗺️ Explore a new part of town|sci 🧲 Do experiments at home",
    "Pick a job at a food festival.|fod 🌮 Cook tacos|wrd 📝 Write reviews of the best food|tec 📱 Make an app for ordering food|bld ⛺ Build the food stands",
    "What would you like to own someday?|biz 🏢 A company|spc 🔭 An observatory|nat 🌳 A forest to protect|ani 🐴 A horse ranch" ],
  [ "Which contest would you enter?|wrd 📝 A story contest|sci 🔬 A science contest|biz 💡 A kids' business idea contest|ani 🐕 A pet trick contest",
    "Which picture would you hang on your wall?|art 🖼️ One you painted|spc 🌌 A photo of a galaxy|saf 🚒 A fire truck poster|adv 🗺️ A map of the world",
    "Pick something to do with friends.|mda 🎮 Play video games together|bld 🏗️ Build a fort|spo 🏐 Play volleyball|prf 🎤 Start a band",
    "How would you help at a hospital?|tea 📚 Read stories to sick kids|car 🎈 Bring balloons to cheer people up|hlp 🩺 Help the nurses|fod 🍲 Cook healthy food for patients",
    "What would you want in your backyard?|nat 🌳 A giant tree to climb|tec 📡 A satellite dish|lea 🗳️ A clubhouse where you're the president|mec 🏎️ A go-kart track" ],
  [ "Which would you like to design?|art 👕 A t-shirt|spc 🛸 A spaceship|hlp 🦽 A better wheelchair|spo 👟 Running shoes",
    "Pick a story to write.|wrd 🕵️ A mystery|ani 🦊 A story about a clever fox|bld 🏰 How a castle was built|saf 🚒 A brave firefighter's rescue",
    "What would you do on a school trip to a farm?|mda 📸 Film everything for a vlog|fod 🧀 Learn how cheese is made|tea 🧒 Explain things to the younger kids|nat 🌾 Learn how crops grow",
    "Which sounds most fun to figure out?|mec ⚙️ How a car engine works|sci 🌈 How rainbows form|car 🤝 How to help people get along|tec 💻 How video games are coded",
    "Pick your role on a group trip.|prf 🎶 The one who sings on the bus|adv 🧭 The navigator|lea 📋 The leader|biz 💰 The one who handles the money" ],
  [ "Which would you rather see?|spc 🌑 A solar eclipse|nat 🌋 A glowing volcano|lea 🏛️ Inside the country's parliament|bld 🗼 The top of the world's tallest building",
    "How would you like to earn money?|wrd ✍️ Writing stories|mec 🔧 Fixing bikes|fod 🥐 Selling baked goods|biz 📈 Buying and selling trading cards",
    "Pick your job on a science TV show.|mda 🎥 Film the experiments|sci 🧪 Do the experiments|hlp 🫀 Explain how the body works|art 🎨 Draw the pictures",
    "What would you do at a sleepover party?|saf 🔦 Be in charge of flashlights and safety|tec 🎮 Set up the video games|car 🫂 Make sure nobody feels left out|prf 🎤 Start a karaoke contest",
    "Pick a weekend adventure.|adv ⛰️ Hike to the top of a hill|ani 🐦 Go bird watching|tea 🚲 Teach a friend to ride a bike|spo 🏊 Go swimming" ],
  [ "What would you make from junk in the garage?|mec 🚗 A soapbox car|bld 🪑 A chair|nat 🪴 Plant pots for flowers|prf 🥁 A drum kit",
    "Pick a book from the library.|wrd 📕 A book of poems|adv 🌍 An explorer's diary|fod 🍰 A kids' cookbook|spc 🪐 A book about planets",
    "What would you do at a pet shelter?|mda 📸 Take photos so pets get adopted|hlp 💉 Help the vet give shots|ani 🐕 Walk the dogs|car 🏡 Help families find the right pet",
    "Pick a role at school.|lea 🗳️ Class president|tea 🧑‍🏫 Homework helper|art 🎨 Art room helper|tec 💻 Computer lab helper",
    "Which of these would you sign up for?|spo 🥋 Judo|saf 🛟 A lifeguard course|biz 💼 Running a pretend company|sci 🔭 Being a scientist for a day" ],
  [ "Which app would you make?|tec 📱 A homework helper app|prf 🎵 A music-making app|biz 🛒 A shopping app|ani 🐾 A pet care app",
    "At a busy restaurant, you'd…|mec 🔧 Fix the broken oven|hlp 🩹 Help if someone gets hurt|fod 👨‍🍳 Cook the food|lea 📋 Manage the whole team",
    "Pick a model to make.|bld 🏙️ A model city|spc 🌍 A model solar system|wrd 📖 A pop-up book|tea 🧮 A model that teaches fractions",
    "What would you do at the beach?|saf 🛟 Watch for swimmers in trouble|art 🏰 Make sand sculptures|adv 🤿 Snorkel to find fish|car 🧹 Pick up trash so everyone can enjoy it",
    "Pick a video to watch.|sci 🧪 Crazy science experiments|mda 🎬 Behind the scenes of a movie|spo ⚽ The best goals ever|nat 🌋 Amazing volcano eruptions" ],
  [ "What would you do for a family dinner?|fod 🍝 Cook the whole meal|wrd 📝 Write place cards with poems|art 🕯️ Decorate the table|prf 🎻 Play music during dinner",
    "Which grown-up would you follow for a day?|hlp 🩺 A doctor|tea 🍎 A teacher|biz 💼 A business owner|sci 🔬 A scientist",
    "Pick a job at a movie studio.|mda 🎥 Camera operator|mec 🚗 Stunt car mechanic|spc 🌌 Making space scenes look real|car 🧃 Looking after the kid actors",
    "At a sports day, you would…|bld 🏗️ Set up the obstacle course|spo 🏅 Compete in every race|lea 📣 Be team captain|saf 🦺 Keep everyone safe",
    "Pick a nature gadget.|nat 🌡️ A weather station|ani 📷 A camera to watch birds|tec 🤖 A robot gardener|adv 🧭 A GPS for hiking" ],
  [ "Pick a school subject to do extra of.|sci 🔬 Science|tec 💻 Computing|wrd 📚 English|lea 🏛️ Government and how laws work",
    "Which vehicle would you ride in?|bld 🏗️ A bulldozer|adv 🎈 A hot air balloon|mec 🏍️ A motorbike|saf 🚑 An ambulance",
    "Pick a way to stay active.|spo 🏊 Swim laps|hlp 🧘 Do yoga to stay healthy|nat 🌲 Hike in the woods|prf 💃 Dance class",
    "You're starting a club. It's a…|mda 🎬 Movie club|biz 💰 Money and business club|art 🖌️ Comic drawing club|tea 📚 Homework help club",
    "Pick a special day out.|fod 🍦 An ice cream factory tour|car 🏡 Helping at a community center|ani 🐧 Meeting penguins|spc 🚀 A space center" ],
  [ "Pick a TV job.|mda 📺 TV director|fod 🍳 TV chef|prf 🎤 Singer on a music show|spo 🏆 Athlete on a game show",
    "Pick something to design.|spc 🛰️ A satellite|art 📘 A comic book cover|hlp 🩺 A robot nurse|mec 🏎️ A race car",
    "Pick a mystery to solve.|sci 🧬 Why some animals glow in the dark|wrd 📜 Who wrote a secret letter|lea ⚖️ Who broke the class rule|ani 🐾 Whose footprints are in the mud",
    "Pick a business to start with friends.|bld 🛠️ A fix-it service|tec 💻 A website-making business|biz 🏪 A snack shop|tea 📚 A tutoring service",
    "After a big storm, you'd…|car 🫂 Check on your neighbors|nat 🌳 Replant fallen trees|adv 🥾 Explore how the land changed|saf 🚧 Help block off dangerous areas" ],
  [ "Pick an exciting job for a day.|hlp 🏥 Emergency room nurse|adv 🌍 Safari guide|saf 🚒 Firefighter|mec ✈️ Airplane mechanic",
    "What would you do at a food truck festival?|fod 🌭 Cook in a truck|tec 📱 Run the ordering app|mda 📸 Post photos online|lea 📋 Organize the whole festival",
    "Pick a project for your backyard.|bld 🏡 Build a shed|tea 🧑‍🏫 Set up an outdoor classroom|nat 🥕 Grow vegetables|ani 🐔 Keep chickens",
    "What would you do at a school fundraiser?|spo 🏃 Run a sponsored race|wrd 📝 Write a newsletter about it|car 🤝 Welcome everyone at the door|biz 💵 Count the money raised",
    "What would you like to see at a museum?|sci 🦖 Dinosaur skeletons|spc 🪐 Moon rocks|prf 🎸 Famous musical instruments|art 🖼️ Famous paintings" ],
  [ "Pick a way to help younger kids.|tea 📖 Teach them to read|art 🖍️ Do crafts with them|ani 🐰 Show them how to care for a bunny|saf 🚸 Teach them to cross the road safely",
    "Pick a dream trip.|prf 🎭 A big musical in New York|spc 🚀 A rocket launch in Florida|adv 🐪 A camel ride in the desert|wrd 📚 The home of a famous author",
    "Pick a weekend plan.|biz 🏷️ Sell your old toys|fod 🥞 Make pancakes for everyone|nat 🦆 Feed ducks at the pond|spo 🚴 Go on a long bike ride",
    "A friend is being bullied. You…|car 🫂 Stand with them and be kind|tec 💻 Design an app to report bullying|hlp 🧠 Help them feel better inside|lea 📣 Ask the principal for a new rule",
    "Which behind-the-scenes job sounds cool?|mda 🎚️ Sound and lights at a concert|mec 🔧 Pit crew at a car race|sci 🧪 Testing new medicines in a lab|bld 🏗️ Building the set for a movie" ],
  [ "At school, you'd like to be in charge of…|mec 🔧 Fixing broken things|tea 📚 Helping kids learn|prf 🎵 The music for assemblies|lea 📋 The student council",
    "Which would you like to do most?|ani 🐋 Watch whales|spc 🌠 Watch a meteor shower|spo 🏂 Snowboard down a mountain|adv ⛵ Sail across a lake",
    "Pick a poster to make.|saf 🚨 How to stay safe at home|nat 🌍 How to save the planet|art 🎨 A colorful mural design|tec 💻 How computers work",
    "Pick something to do at a community event.|fod 🍔 Help grill burgers|car 🎈 Run games for little kids|bld 🎪 Set up the tents|sci 🔬 Run a science demo",
    "What would you like to read about?|hlp 🦴 How bones heal|biz 💰 How kids started big companies|wrd 📖 Famous poems|mda 🎮 How video games are made" ],
  [ "Which would you like to test?|sci 🧪 A new chemical|mec 🚗 A new car|mda 🎮 A new video game|adv 🎒 New hiking gear on a real trip",
    "Pick a job for the future.|spc 🌕 Moon explorer|biz 🏢 Businessperson|saf 🦺 Rescue worker|nat 🌱 Planet protector",
    "What would you do at a school sleepover?|tec 💻 Code a game for everyone|fod 🍿 Make popcorn and snacks|tea 🧩 Teach everyone a new game|prf 🎤 Put on a show",
    "Pick a job helping your town.|wrd 📰 Writing the town newsletter|ani 🐕 Running the dog park|hlp 🏥 Helping at the clinic|lea 🏛️ Being on the town council",
    "Pick an afternoon project.|art 🎨 Paint rocks|spo 🏀 Practise free throws|bld 🪵 Build a bird feeder|car 💐 Make cards for people in hospital" ],
  [ "Which class would you take?|fod 🍰 Cake decorating|tea 🧑‍🏫 How to be a camp counselor|saf 🩹 A babysitting safety course|spc 🔭 Astronomy",
    "On a sports team, you'd be…|car 🤝 The one who cheers everyone up|lea 🧑‍✈️ The captain|bld 🏟️ The one who builds the new clubhouse|spo ⚡ The star player",
    "Pick something to do on a long trip.|adv 🗺️ Plan where to stop next|biz 💵 Keep track of the trip budget|mda 📹 Vlog the whole trip|tec 💻 Code a travel game",
    "Which would you rather study?|sci 🧫 Bacteria|wrd 🗣️ Languages|ani 🦈 Sharks|mec ⚙️ Machines",
    "What would you do at a garden party?|prf 🎻 Play music|nat 🌹 Show off the flowers|hlp 💧 Make sure everyone drinks water in the heat|art 🖌️ Paint the garden" ],
  [ "What would you like to grow or make?|sci 💎 Crystals|tec 🤖 A robot pet|fod 🍓 Strawberry jam|nat 🌻 Sunflowers taller than you",
    "Which volunteer job would you do?|hlp 🏥 Hospital helper|adv 🌍 Helping in another country|ani 🐶 Animal shelter helper|car 👵 Care home helper",
    "Which would you like to watch live?|spo 🏟️ A big football game|mec 🏁 A car race|mda 🎬 A movie premiere|spc 🚀 A rocket taking off",
    "What would you do in a school play?|biz 🎟️ Sell the tickets|prf 🎭 Play the lead role|saf 🧯 Be the safety crew|lea 📋 Direct the play",
    "Pick a craft kit.|bld 🏠 A dollhouse to build|tea 📚 A kit to make flashcards for kids|art 🎨 A painting kit|wrd ✒️ A fancy handwriting kit" ],
  [ "Pick a project for the school garden.|art 🎨 Paint colorful signs|lea 📋 Plan who does what|bld 🪵 Build the garden beds|ani 🐛 Build a home for bugs",
    "What would you do at a career day?|biz 💼 Visit the business owner|tea 🍎 Visit the teacher|hlp 🩺 Visit the doctor|sci 🔬 Visit the scientist",
    "Pick something to do with a laptop.|prf 🎹 Make music|tec 💻 Write code|mda ✂️ Edit a movie|adv 🗺️ Plan a trip around the world",
    "What would you do at a campfire?|nat 🌌 Listen to the night animals|car 🍫 Share s'mores with everyone|wrd 👻 Tell spooky stories|saf 🔥 Make sure the fire stays safe",
    "Pick a theme park ride.|spc 🚀 A rocket simulator|spo 🧗 A climbing wall|mec 🏎️ Bumper cars|fod 🍭 A candy factory ride" ],
  [ "Which would you rather win?|spo 🏆 A sports trophy|wrd 📚 A writing prize|spc 🔭 A trip to space camp|tec 💻 A coding contest",
    "What would you like to do on a boat trip?|bld ⚓ Help build the boat|adv 🧭 Steer to new places|mda 📸 Film the dolphins|fod 🐟 Cook fish for dinner",
    "Pick a school rule you'd make.|nat 🌱 Every class plants a tree|ani 🐶 Pets can visit on Fridays|lea ⚖️ Everyone gets a vote|art 🎨 Art every day",
    "You get $20. You'd…|car 🎁 Buy a gift for someone who needs it|mec 🔧 Buy parts to fix your bike|biz 📈 Save it and grow it|tea 📚 Buy books to share with kids",
    "Pick a superpower.|hlp ✨ Heal any sickness|saf 🦸 Save people from danger|sci 🧠 Know how everything works|prf 🎤 The most amazing voice" ],
  [ "Pick something to study up close.|art 🖼️ An old master's painting|mec ⚙️ An old engine|sci 🔬 A flower under a microscope|spc 🛰️ A real satellite",
    "What would you do at a street festival?|fod 🌮 Try every food stall|adv 🎡 Explore every corner|prf 🎭 Perform on the street|biz 💰 Run your own stall",
    "Pick something to make for your class.|nat 🌱 A class plant corner|tea 🧩 A learning game|mda 🎬 A class video|wrd 📖 A class storybook",
    "What would make you proudest?|ani 🐕 Training your dog to do tricks|saf 🚒 Helping in a real emergency|spo 🥇 Winning a medal|lea 🏫 Being chosen as school captain",
    "Pick a gadget to build.|hlp 💓 A heart-rate monitor|tec 📱 A smartphone|car 🔔 A button that calls grandma for help|bld 🏠 A smart house" ],
  [ "Pick a job on a cruise ship.|mec 🔧 Engine room mechanic|hlp 🩺 Cruise ship nurse|wrd 📰 Writer of the daily newsletter|fod 🍝 Ship's chef",
    "What would you do at a town meeting?|lea 🎙️ Speak up for your idea|sci 📊 Show facts and data|car 🤝 Make sure everyone gets heard|tec 💻 Run the online vote",
    "Pick a dream place to live.|adv 🏝️ A tropical island|bld 🏰 A house you designed|biz 🏙️ A big city full of shops and offices|nat 🌲 A cabin in the forest",
    "What would you do at summer camp?|tea 🧑‍🏫 Be a junior counselor|ani 🐎 Go horse riding|prf 🎭 Star in the camp play|spc 🌌 Watch the night sky",
    "Pick a job at a stadium.|mda 📺 Film the game|saf 🦺 Security guard|spo 🏈 Play in the game|art 🎨 Design the team logo" ],
  [ "What would you do on a farm?|mec 🚜 Drive the tractor|nat 🌾 Plant the crops|bld 🏚️ Fix the barn|wrd 📝 Write a blog about farm life",
    "Pick a way to spend a school trip.|tea 🧑‍🏫 Help the teacher with the little kids|art 🖼️ Sketch what you see|adv 🧭 Find the way with a map|lea 📋 Lead your group",
    "Which would you like to create?|spc 🛸 A drone that flies up to the clouds|tec 🧠 An AI helper|mda 🎮 A video game|hlp 🦿 A robot arm for people who need one",
    "At a party, you'd…|prf 🎤 Start the karaoke|car 🫂 Talk to someone who's alone|ani 🐶 Play with the dog|spo 🏐 Start a game of volleyball",
    "Pick a job at a theme park.|fod 🍦 Ice cream stand|biz 🎟️ Ticket booth manager|saf 🦺 Ride safety checker|sci 🔬 Testing how the rides work" ],
  [ "What would you like to be really good at?|hlp 🩹 Making people feel better|biz 💰 Making money grow|art 🎨 Drawing anything|wrd ✍️ Writing amazing stories",
    "Your school trip gets lost. You…|lea 📣 Take charge and calm everyone down|saf 🦺 Keep everyone together and out of danger|car 🫂 Comfort the scared kids|adv 🧭 Find a new way to go",
    "Pick a TV show to make.|mda 😂 A funny show|fod 🍳 A baking competition show|tea 🧑‍🏫 A show that teaches kids|nat 🌿 A show about wild places",
    "Pick a game to play.|ani 🦓 An animal quiz|spo ⚽ Soccer|mec 🏎️ A racing game with real go-karts|tec 💻 A coding puzzle game",
    "Which would you like to discover?|spc 🌍 A new planet|prf 🎶 A new kind of music|bld 🏛️ A new way to build houses|sci 🧬 A new kind of germ" ],
  [ "Pick a job at a museum.|tea 🗺️ Tour guide for school groups|adv 🧭 Explorer who finds new objects|art 🖼️ Painting restorer|mda 📸 Museum photographer",
    "Which would you rather do in summer?|sci 🔬 Science camp|spo 🏊 Swim team|ani 🐬 Dolphin camp|spc 🚀 Space camp",
    "Pick a way to earn pocket money.|fod 🧁 Sell cupcakes|mec 🚲 Fix neighbors' bikes|biz 🏷️ Sell things online|lea 🧑‍💼 Run a team of kids doing chores",
    "What would you do on a quiet evening?|prf 🎹 Play piano|nat 🌙 Watch the sunset|car 📞 Call your grandparents|wrd 📖 Read a book",
    "Which would you like to protect?|saf 🏠 Your town from fires|tec 🔒 Computers from hackers|bld 🌉 Bridges from falling down|hlp 🦠 People from getting sick" ],
  [ "What's your favourite way to spend a holiday?|fod 🍗 Cooking a big holiday meal|spo ⛷️ Skiing|tec 🎮 Playing new games|tea 🧒 Teaching cousins new games",
    "Which job would you try at a newspaper?|hlp 🩺 Health reporter|wrd 📝 Story writer|mda 📸 Photographer|adv ✈️ Travel reporter",
    "Pick a job at a mall.|car 🧸 Helping lost kids find their parents|prf 🎤 Singing on the mall stage|biz 🏪 Store manager|mec 🛗 Fixing the escalators",
    "What would you do on a nature walk?|nat 🍄 Find mushrooms and plants|sci 🔍 Collect samples to study|saf 🧭 Make sure no one gets lost|ani 🦌 Look for deer tracks",
    "Pick a thing you'd want to lead.|spc 🚀 A mission to Mars|lea 🏛️ A country|art 🎨 A team of artists|bld 🏗️ A team building a skyscraper" ],
  [ "Pick a job at a wedding.|lea 📋 Wedding planner|bld ⛺ Build the stage and tent|fod 🎂 Bake the wedding cake|prf 🎻 Play the music",
    "Which would you rather do after school?|mec 🔧 Tinker in the garage|biz 💵 Run a small business|wrd 📓 Write in your journal|saf 🥋 Learn self-defense",
    "What would you make for a sick friend?|car 💐 A care package|art 🎨 A get-well painting|tec 📱 A game for their tablet|sci 🧪 A science kit to keep them busy",
    "Pick a job at a sports camp.|tea 📋 Coach the little kids|spo 🏃 Train with the pros|adv 🏕️ Lead the camping trip|hlp 🩹 Be the camp medic",
    "Pick a picture book.|nat 🌈 All about weather|spc 🌟 Stars and planets|mda 🎥 How cartoons are made|ani 🐯 Tigers of the jungle" ],
  [ "Pick a travel plan.|adv 🎒 Backpack across Europe|fod 🍝 A food tour of Italy|art 🖼️ The art museums of Paris|mec 🚄 The fastest trains in Japan",
    "Which would you like to program?|tec 💻 A website|biz 📊 A program that tracks money|saf 🚨 A smart alarm system|spc 🛰️ A Mars rover",
    "At a school sports day, you'd…|spo 🏅 Win the relay|ani 🐕 Run the dog agility show|lea 🧑‍⚖️ Be the head judge|mda 🎙️ Announce the races",
    "What would you do at a family gathering?|tea 🧩 Teach the kids a game|prf 🎶 Sing a song for everyone|car 🫂 Sit with the older relatives|wrd 📜 Write down the family stories",
    "Which problem would you solve?|nat 🌍 Climate change|hlp 💊 A disease with no cure|bld 🏠 Homes for people who don't have one|sci 🔬 A mystery scientists can't explain" ],
];

// Parse into the same shape as OPENERS: { q, a: [[emoji, text, topic], ...] }
const QUESTION_SETS = QUESTION_SETS_TEXT.map(set => set.map(line => {
  const [q, ...answers] = line.split("|");
  return {
    q,
    a: answers.map(ans => {
      const [topic, emoji, ...words] = ans.split(" ");
      return [emoji, words.join(" "), topic];
    }),
  };
}));
