// Pretend sports workers, to check the game can tell sports and roles apart.
// a = where, wear, how got job, do most of day, who with, tools, best, hardest, boss, word, people ask, big clue
module.exports = [
 { job: "Basketball Coach", a: ["a basketball arena and the practice court","a polo shirt and sneakers on the sideline","I played college basketball then coached","run practices and plan plays","players and assistant coaches","a whiteboard and game film","seeing my players grow","losing close games","the general manager","pick and roll","can you get me tickets to a game","I train a basketball team and call the plays"], x: ["timeouts and tactics","drills on the court","we watch film of other teams"] },
 { job: "Basketball Player", a: ["on the court in an arena","a jersey and sneakers","drafted after college","practice and play games","teammates and coaches","a basketball","dunking in front of a crowd","injuries and travel","the coach","rebound","how tall are you","I shoot hoops for a professional team"], x: ["dribbling and shooting","games every few days","training and the gym"] },
 { job: "Basketball Team Owner", a: ["an office at the arena","a suit","I made money in business and bought the team","meet with the general manager and sign big checks","executives and investors","my phone","winning a championship","paying huge salaries","nobody, I own it","payroll","can I meet the players","I own a professional basketball team"], x: ["money and contracts","the business side","I pay the players"] },
 { job: "Tennis Umpire", a: ["sitting high on a chair at the tennis court","a uniform with a cap","umpire courses and certification","call the score and decide if balls are in or out","tennis players and line judges","a microphone and a scoreboard tablet","the best seat in the house","angry players shouting at me","the tournament referee","deuce","do you ever get it wrong","I make the calls and keep score in tennis matches"], x: ["rules and calls","the court","matches at tournaments"] },
 { job: "Ice Hockey Commentator", a: ["a broadcast booth above the rink","a suit and headset","started on college radio","describe hockey games live","the producer and my co analyst","a microphone","a big goal in overtime","talking fast for three hours","the network producer","power play","do you get free tickets","I describe the action on TV during hockey games"], x: ["the puck and the rink","live broadcasts","I talk on TV"] },
 { job: "Cricket Coach", a: ["the cricket ground and the nets","a tracksuit","I played cricket then got coaching badges","run training sessions and plan tactics","batsmen and bowlers","bats, balls and stumps","watching players improve","bad weather cancelling matches","the director of cricket","wicket","can you fix my batting","I train a cricket team"], x: ["bowling and batting drills","matches on the weekend","tactics"] },
 { job: "Boxing Promoter", a: ["an office and at fight nights","a sharp suit","I started as a manager of boxers","set up fights and sell tickets","boxers, managers and TV people","my phone and contracts","a sold out arena","boxers pulling out of fights","myself","main event","can you get me ringside seats","I put on boxing fights and sell the tickets"], x: ["fight nights","money and TV deals","the ring"] },
 { job: "Football Club Owner", a: ["the director's box at the stadium","a suit","I made money in business","approve transfers and talk to the manager","the board and the manager","my phone","winning the league","losing money","nobody, it's my club","transfer budget","can I meet the players","I own a football club and pay for the players"], x: ["the squad and transfers","money","the stadium"] },
];
