// 15 pretend workers answering the current short questions (written after they changed).
// a = where, wear, how got job, do most of day, who with, tools, best, hardest, boss, word, people ask, big clue
module.exports = [
 { job: "Nurse", a: ["a hospital","scrubs","nursing degree at university","look after patients and give medicine","patients and doctors","a stethoscope and a blood pressure cuff","helping people get better","twelve hour shifts","the ward manager","stat","can you look at my rash","I care for sick people in hospital"], x: ["I check vitals","long night shifts","patients"] },
 { job: "Electrician", a: ["houses and building sites","work boots and hi vis","an apprenticeship","wiring houses and fixing faults","homeowners and builders","wire strippers and a tester","fixing a fault nobody else could","getting shocked","I'm my own boss","live wire","can you fix my lights","I make the power and lights work"], x: ["sockets and fuse boxes","electricity","wiring"] },
 { job: "Teacher", a: ["a school","smart casual","a teaching degree","teach lessons and mark homework","kids","a whiteboard and laptop","when kids finally get it","marking and behaviour","the headteacher","homework","do you get summers off","I help kids learn"], x: ["I teach nine year olds","lessons","maths and reading"] },
 { job: "Software Developer", a: ["an office or at home","whatever I want","computer science at university","write code","my team","a laptop","solving problems","bugs","the engineering manager","deploy","can you fix my computer","I build apps"], x: ["javascript and python","I fix bugs","code reviews"] },
 { job: "Chef", a: ["a restaurant kitchen","chef whites","culinary school","cook food","the kitchen team","knives, pans and ovens","making new dishes","the heat and long hours","the head chef","yes chef","can you cook for my party","I cook meals at a restaurant"], x: ["the menu","sauces and grilling","dinner service"] },
 { job: "Police Officer", a: ["out on the streets","a uniform","police academy","patrol and answer calls","the public","a radio and handcuffs","helping people","dangerous situations","the sergeant","suspect","have you arrested anyone","I keep people safe and catch criminals"], x: ["I arrest people","crime","emergencies"] },
 { job: "Hairstylist", a: ["a salon","all black","beauty school","cut and colour hair","clients","scissors and a hairdryer","making people feel good","standing all day","the salon owner","balayage","can you do my hair","I make people's hair look good"], x: ["haircuts","colour and styling","the salon"] },
 { job: "Truck Driver", a: ["on the road","jeans","truck licence","drive","dispatchers","my truck","seeing the country","being away from home","the dispatcher","eighteen wheeler","where do you go","I deliver goods across the country"], x: ["freight","the highway","long hauls"] },
 { job: "Accountant", a: ["an office","a suit","accounting degree","spreadsheets and taxes","clients","excel and a calculator","getting the numbers right","tax season","the partner","invoice","can you do my taxes","I look after money for businesses"], x: ["taxes and audits","financial reports","numbers"] },
 { job: "Veterinarian", a: ["an animal clinic","scrubs","veterinary school","treat sick animals","pets and their owners","a stethoscope","saving animals","when animals die","the clinic owner","spay","can you look at my dog","I help animals get better"], x: ["dogs and cats","surgery and vaccines","pets"] },
 { job: "Cashier", a: ["a supermarket","a uniform and name tag","no school needed","scan items and take payment","customers","the till and a scanner","nice customers","rude customers","the store manager","price check","do you get a discount","I ring up people's shopping"], x: ["the checkout","groceries","customers pay me"] },
 { job: "Plumber", a: ["in people's homes","overalls","an apprenticeship","fix leaks","homeowners","a wrench and pipes","fixing a big leak","sewage","I'm my own boss","p trap","can you fix my toilet","I fix pipes and toilets"], x: ["drains and boilers","leaks","pipes"] },
 { job: "Farmer", a: ["outside on a farm","overalls and boots","I grew up on the farm","feed animals and plant crops","cows","a tractor","being outdoors","the weather","myself","harvest","do you get up early","I grow food and raise animals"], x: ["crops","the tractor","cows and sheep"] },
 { job: "Football Manager", a: ["a football stadium and training ground","a tracksuit","coaching badges after playing","plan tactics and pick the team","players and coaches","a tactics board","winning matches","getting sacked","the club owner","formation","who's your best player","I pick the team and plan tactics for a football club"], x: ["the squad and transfers","matches every weekend","press conferences"] },
 { job: "Graphic Designer", a: ["an office","casual","art school","design logos and posters","clients","a laptop and photoshop","being creative","picky clients","the creative director","kerning","can you design my logo","I make things look good for brands"], x: ["branding","adverts","illustrator"] },
];
